[2025-06-17T02:25:26.509+0000] {taskinstance.py:1042} DEBUG - previous_execution_date was called
[2025-06-17T02:25:26.635+0000] {__init__.py:54} DEBUG - Loading core task runner: StandardTaskRunner
[2025-06-17T02:25:26.668+0000] {taskinstance.py:1042} DEBUG - previous_execution_date was called
[2025-06-17T02:25:26.706+0000] {base_task_runner.py:73} DEBUG - Planning to run as the  user
[2025-06-17T02:25:26.718+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-17T02:25:26.876+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.transform.transform_dim_locations scheduled__2025-06-16T00:00:00+00:00 [queued]> dependency 'Task Instance State' PASSED: True, Task state queued was valid.
[2025-06-17T02:25:26.880+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.transform.transform_dim_locations scheduled__2025-06-16T00:00:00+00:00 [queued]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2025-06-17T02:25:26.900+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.transform.transform_dim_locations scheduled__2025-06-16T00:00:00+00:00 [queued]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2025-06-17T02:25:26.906+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.transform.transform_dim_locations scheduled__2025-06-16T00:00:00+00:00 [queued]> dependency 'Task Instance Not Running' PASSED: True, Task is not in running state.
[2025-06-17T02:25:26.910+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: globalsuperstore.transform.transform_dim_locations scheduled__2025-06-16T00:00:00+00:00 [queued]>
[2025-06-17T02:25:26.917+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.transform.transform_dim_locations scheduled__2025-06-16T00:00:00+00:00 [queued]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2025-06-17T02:25:26.923+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.transform.transform_dim_locations scheduled__2025-06-16T00:00:00+00:00 [queued]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2025-06-17T02:25:26.941+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.transform.transform_dim_locations scheduled__2025-06-16T00:00:00+00:00 [queued]> dependency 'Pool Slots Available' PASSED: True, There are enough open slots in default_pool to execute the task
[2025-06-17T02:25:26.944+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.transform.transform_dim_locations scheduled__2025-06-16T00:00:00+00:00 [queued]> dependency 'Task Concurrency' PASSED: True, Task concurrency is not set.
[2025-06-17T02:25:26.946+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: globalsuperstore.transform.transform_dim_locations scheduled__2025-06-16T00:00:00+00:00 [queued]>
[2025-06-17T02:25:26.947+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-06-17T02:25:27.011+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transform.transform_dim_locations> on 2025-06-16 00:00:00+00:00
[2025-06-17T02:25:27.046+0000] {standard_task_runner.py:63} INFO - Started process 231 to run task
[2025-06-17T02:25:27.055+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'globalsuperstore', 'transform.transform_dim_locations', 'scheduled__2025-06-16T00:00:00+00:00', '--job-id', '377', '--raw', '--subdir', 'DAGS_FOLDER/global_superstore_dw_etl.py', '--cfg-path', '/tmp/tmpsin277py']
[2025-06-17T02:25:27.060+0000] {standard_task_runner.py:91} INFO - Job 377: Subtask transform.transform_dim_locations
[2025-06-17T02:25:27.065+0000] {cli_action_loggers.py:70} DEBUG - Calling callbacks: [<function default_action_log at 0x7fdcec52d750>]
[2025-06-17T02:25:27.200+0000] {taskinstance.py:1042} DEBUG - previous_execution_date was called
[2025-06-17T02:25:27.211+0000] {task_command.py:426} INFO - Running <TaskInstance: globalsuperstore.transform.transform_dim_locations scheduled__2025-06-16T00:00:00+00:00 [running]> on host 9b7c60adfed6
[2025-06-17T02:25:27.212+0000] {settings.py:363} DEBUG - Disposing DB connection pool (PID 231)
[2025-06-17T02:25:27.214+0000] {settings.py:250} DEBUG - Setting up DB connection pool (PID 231)
[2025-06-17T02:25:27.214+0000] {settings.py:298} DEBUG - settings.prepare_engine_args(): Using NullPool
[2025-06-17T02:25:27.315+0000] {taskinstance.py:1042} DEBUG - previous_execution_date was called
[2025-06-17T02:25:27.330+0000] {taskinstance.py:1845} DEBUG - Clearing XCom data
[2025-06-17T02:25:27.364+0000] {retries.py:91} DEBUG - Running RenderedTaskInstanceFields.write with retries. Try 1 of 3
[2025-06-17T02:25:27.429+0000] {retries.py:91} DEBUG - Running RenderedTaskInstanceFields._do_delete_old_records with retries. Try 1 of 3
[2025-06-17T02:25:27.464+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='globalsuperstore' AIRFLOW_CTX_TASK_ID='transform.transform_dim_locations' AIRFLOW_CTX_EXECUTION_DATE='2025-06-16T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-06-16T00:00:00+00:00'
[2025-06-17T02:25:27.465+0000] {__init__.py:115} DEBUG - Preparing lineage inlets and outlets
[2025-06-17T02:25:27.466+0000] {__init__.py:154} DEBUG - inlets: [], outlets: []
[2025-06-17T02:25:27.468+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-17T02:25:27.537+0000] {base.py:84} INFO - Using connection ID 'postgres' for task execution.
[2025-06-17T02:25:27.564+0000] {base.py:84} INFO - Using connection ID 'postgres' for task execution.
[2025-06-17T02:25:27.593+0000] {base.py:84} INFO - Using connection ID 'postgres' for task execution.
[2025-06-17T02:25:27.627+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/***/providers/common/sql/hooks/sql.py:263 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2025-06-17T02:25:29.207+0000] {logging_mixin.py:188} INFO - ✔ Đã lưu dữ liệu vào warehouse.dim_location (3777 dòng)
[2025-06-17T02:25:29.208+0000] {logging_mixin.py:188} INFO - ✔ Đã transform và lưu dữ liệu vào warehouse.dim_location
[2025-06-17T02:25:29.230+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-06-17T02:25:29.231+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-17T02:25:29.233+0000] {__init__.py:77} DEBUG - Lineage called with inlets: [], outlets: []
[2025-06-17T02:25:29.244+0000] {taskinstance.py:584} DEBUG - Clearing next_method and next_kwargs.
[2025-06-17T02:25:29.245+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=globalsuperstore, task_id=transform.transform_dim_locations, run_id=scheduled__2025-06-16T00:00:00+00:00, execution_date=20250616T000000, start_date=20250617T022526, end_date=20250617T022529
[2025-06-17T02:25:29.245+0000] {taskinstance.py:562} DEBUG - Task Duration set to 2.333732
[2025-06-17T02:25:29.255+0000] {cli_action_loggers.py:88} DEBUG - Calling callbacks: []
[2025-06-17T02:25:29.315+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-06-17T02:25:29.340+0000] {dagrun.py:931} DEBUG - number of tis tasks for <DagRun globalsuperstore @ 2025-06-16 00:00:00+00:00: scheduled__2025-06-16T00:00:00+00:00, state:running, queued_at: 2025-06-17 02:25:04.605711+00:00. externally triggered: False>: 6 task(s)
[2025-06-17T02:25:29.341+0000] {dagrun.py:952} DEBUG - number of scheduleable tasks for <DagRun globalsuperstore @ 2025-06-16 00:00:00+00:00: scheduled__2025-06-16T00:00:00+00:00, state:running, queued_at: 2025-06-17 02:25:04.605711+00:00. externally triggered: False>: 0 task(s)
[2025-06-17T02:25:29.342+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-17T02:25:29.346+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-06-17T02:27:50.420+0000] {taskinstance.py:1042} DEBUG - previous_execution_date was called
[2025-06-17T02:27:50.500+0000] {__init__.py:54} DEBUG - Loading core task runner: StandardTaskRunner
[2025-06-17T02:27:50.579+0000] {taskinstance.py:1042} DEBUG - previous_execution_date was called
[2025-06-17T02:27:50.631+0000] {base_task_runner.py:73} DEBUG - Planning to run as the  user
[2025-06-17T02:27:50.665+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-17T02:27:50.879+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.transform.transform_dim_locations scheduled__2025-06-16T00:00:00+00:00 [queued]> dependency 'Task Instance Not Running' PASSED: True, Task is not in running state.
[2025-06-17T02:27:50.897+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.transform.transform_dim_locations scheduled__2025-06-16T00:00:00+00:00 [queued]> dependency 'Task Instance State' PASSED: True, Task state queued was valid.
[2025-06-17T02:27:50.899+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.transform.transform_dim_locations scheduled__2025-06-16T00:00:00+00:00 [queued]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2025-06-17T02:27:50.900+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.transform.transform_dim_locations scheduled__2025-06-16T00:00:00+00:00 [queued]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2025-06-17T02:27:50.900+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: globalsuperstore.transform.transform_dim_locations scheduled__2025-06-16T00:00:00+00:00 [queued]>
[2025-06-17T02:27:50.935+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.transform.transform_dim_locations scheduled__2025-06-16T00:00:00+00:00 [queued]> dependency 'Pool Slots Available' PASSED: True, There are enough open slots in default_pool to execute the task
[2025-06-17T02:27:50.940+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.transform.transform_dim_locations scheduled__2025-06-16T00:00:00+00:00 [queued]> dependency 'Task Concurrency' PASSED: True, Task concurrency is not set.
[2025-06-17T02:27:50.948+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.transform.transform_dim_locations scheduled__2025-06-16T00:00:00+00:00 [queued]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2025-06-17T02:27:50.950+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.transform.transform_dim_locations scheduled__2025-06-16T00:00:00+00:00 [queued]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2025-06-17T02:27:50.951+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: globalsuperstore.transform.transform_dim_locations scheduled__2025-06-16T00:00:00+00:00 [queued]>
[2025-06-17T02:27:50.951+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-06-17T02:27:51.120+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transform.transform_dim_locations> on 2025-06-16 00:00:00+00:00
[2025-06-17T02:27:51.159+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'globalsuperstore', 'transform.transform_dim_locations', 'scheduled__2025-06-16T00:00:00+00:00', '--job-id', '382', '--raw', '--subdir', 'DAGS_FOLDER/global_superstore_dw_etl.py', '--cfg-path', '/tmp/tmppok99yen']
[2025-06-17T02:27:51.153+0000] {standard_task_runner.py:63} INFO - Started process 230 to run task
[2025-06-17T02:27:51.167+0000] {standard_task_runner.py:91} INFO - Job 382: Subtask transform.transform_dim_locations
[2025-06-17T02:27:51.177+0000] {cli_action_loggers.py:70} DEBUG - Calling callbacks: [<function default_action_log at 0x7f821ad2d750>]
[2025-06-17T02:27:51.340+0000] {taskinstance.py:1042} DEBUG - previous_execution_date was called
[2025-06-17T02:27:51.352+0000] {task_command.py:426} INFO - Running <TaskInstance: globalsuperstore.transform.transform_dim_locations scheduled__2025-06-16T00:00:00+00:00 [running]> on host 9b7c60adfed6
[2025-06-17T02:27:51.353+0000] {settings.py:363} DEBUG - Disposing DB connection pool (PID 230)
[2025-06-17T02:27:51.358+0000] {settings.py:250} DEBUG - Setting up DB connection pool (PID 230)
[2025-06-17T02:27:51.361+0000] {settings.py:298} DEBUG - settings.prepare_engine_args(): Using NullPool
[2025-06-17T02:27:51.482+0000] {taskinstance.py:1042} DEBUG - previous_execution_date was called
[2025-06-17T02:27:51.499+0000] {taskinstance.py:1845} DEBUG - Clearing XCom data
[2025-06-17T02:27:51.596+0000] {retries.py:91} DEBUG - Running RenderedTaskInstanceFields.write with retries. Try 1 of 3
[2025-06-17T02:27:51.656+0000] {retries.py:91} DEBUG - Running RenderedTaskInstanceFields._do_delete_old_records with retries. Try 1 of 3
[2025-06-17T02:27:51.717+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='globalsuperstore' AIRFLOW_CTX_TASK_ID='transform.transform_dim_locations' AIRFLOW_CTX_EXECUTION_DATE='2025-06-16T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-06-16T00:00:00+00:00'
[2025-06-17T02:27:51.718+0000] {__init__.py:115} DEBUG - Preparing lineage inlets and outlets
[2025-06-17T02:27:51.720+0000] {__init__.py:154} DEBUG - inlets: [], outlets: []
[2025-06-17T02:27:51.727+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-17T02:27:51.818+0000] {base.py:84} INFO - Using connection ID 'postgres' for task execution.
[2025-06-17T02:27:51.850+0000] {base.py:84} INFO - Using connection ID 'postgres' for task execution.
[2025-06-17T02:27:51.882+0000] {base.py:84} INFO - Using connection ID 'postgres' for task execution.
[2025-06-17T02:27:52.075+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/***/providers/common/sql/hooks/sql.py:263 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2025-06-17T02:27:54.639+0000] {logging_mixin.py:188} INFO - ✔ Đã lưu dữ liệu vào warehouse.dim_location (3777 dòng)
[2025-06-17T02:27:54.640+0000] {logging_mixin.py:188} INFO - ✔ Đã transform và lưu dữ liệu vào warehouse.dim_location
[2025-06-17T02:27:54.664+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-06-17T02:27:54.666+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-17T02:27:54.667+0000] {__init__.py:77} DEBUG - Lineage called with inlets: [], outlets: []
[2025-06-17T02:27:54.678+0000] {taskinstance.py:584} DEBUG - Clearing next_method and next_kwargs.
[2025-06-17T02:27:54.679+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=globalsuperstore, task_id=transform.transform_dim_locations, run_id=scheduled__2025-06-16T00:00:00+00:00, execution_date=20250616T000000, start_date=20250617T022750, end_date=20250617T022754
[2025-06-17T02:27:54.680+0000] {taskinstance.py:562} DEBUG - Task Duration set to 3.777862
[2025-06-17T02:27:54.691+0000] {cli_action_loggers.py:88} DEBUG - Calling callbacks: []
[2025-06-17T02:27:54.748+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-06-17T02:27:54.777+0000] {dagrun.py:931} DEBUG - number of tis tasks for <DagRun globalsuperstore @ 2025-06-16 00:00:00+00:00: scheduled__2025-06-16T00:00:00+00:00, state:running, queued_at: 2025-06-17 02:27:23.275803+00:00. externally triggered: False>: 6 task(s)
[2025-06-17T02:27:54.778+0000] {dagrun.py:952} DEBUG - number of scheduleable tasks for <DagRun globalsuperstore @ 2025-06-16 00:00:00+00:00: scheduled__2025-06-16T00:00:00+00:00, state:running, queued_at: 2025-06-17 02:27:23.275803+00:00. externally triggered: False>: 0 task(s)
[2025-06-17T02:27:54.778+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-17T02:27:54.782+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-06-17T02:33:10.905+0000] {taskinstance.py:1042} DEBUG - previous_execution_date was called
[2025-06-17T02:33:10.990+0000] {__init__.py:54} DEBUG - Loading core task runner: StandardTaskRunner
[2025-06-17T02:33:11.037+0000] {taskinstance.py:1042} DEBUG - previous_execution_date was called
[2025-06-17T02:33:11.065+0000] {base_task_runner.py:73} DEBUG - Planning to run as the  user
[2025-06-17T02:33:11.128+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-17T02:33:11.326+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.transform.transform_dim_locations scheduled__2025-06-16T00:00:00+00:00 [queued]> dependency 'Task Instance Not Running' PASSED: True, Task is not in running state.
[2025-06-17T02:33:11.343+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.transform.transform_dim_locations scheduled__2025-06-16T00:00:00+00:00 [queued]> dependency 'Task Instance State' PASSED: True, Task state queued was valid.
[2025-06-17T02:33:11.344+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.transform.transform_dim_locations scheduled__2025-06-16T00:00:00+00:00 [queued]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2025-06-17T02:33:11.345+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.transform.transform_dim_locations scheduled__2025-06-16T00:00:00+00:00 [queued]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2025-06-17T02:33:11.346+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: globalsuperstore.transform.transform_dim_locations scheduled__2025-06-16T00:00:00+00:00 [queued]>
[2025-06-17T02:33:11.371+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.transform.transform_dim_locations scheduled__2025-06-16T00:00:00+00:00 [queued]> dependency 'Pool Slots Available' PASSED: True, There are enough open slots in default_pool to execute the task
[2025-06-17T02:33:11.373+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.transform.transform_dim_locations scheduled__2025-06-16T00:00:00+00:00 [queued]> dependency 'Task Concurrency' PASSED: True, Task concurrency is not set.
[2025-06-17T02:33:11.381+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.transform.transform_dim_locations scheduled__2025-06-16T00:00:00+00:00 [queued]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2025-06-17T02:33:11.385+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.transform.transform_dim_locations scheduled__2025-06-16T00:00:00+00:00 [queued]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2025-06-17T02:33:11.386+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: globalsuperstore.transform.transform_dim_locations scheduled__2025-06-16T00:00:00+00:00 [queued]>
[2025-06-17T02:33:11.388+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-06-17T02:33:11.481+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transform.transform_dim_locations> on 2025-06-16 00:00:00+00:00
[2025-06-17T02:33:11.509+0000] {standard_task_runner.py:63} INFO - Started process 436 to run task
[2025-06-17T02:33:11.564+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'globalsuperstore', 'transform.transform_dim_locations', 'scheduled__2025-06-16T00:00:00+00:00', '--job-id', '409', '--raw', '--subdir', 'DAGS_FOLDER/global_superstore_dw_etl.py', '--cfg-path', '/tmp/tmp65412nyz']
[2025-06-17T02:33:11.589+0000] {standard_task_runner.py:91} INFO - Job 409: Subtask transform.transform_dim_locations
[2025-06-17T02:33:11.626+0000] {cli_action_loggers.py:70} DEBUG - Calling callbacks: [<function default_action_log at 0x7f821ad2d750>]
[2025-06-17T02:33:11.823+0000] {taskinstance.py:1042} DEBUG - previous_execution_date was called
[2025-06-17T02:33:11.851+0000] {task_command.py:426} INFO - Running <TaskInstance: globalsuperstore.transform.transform_dim_locations scheduled__2025-06-16T00:00:00+00:00 [running]> on host 9b7c60adfed6
[2025-06-17T02:33:11.861+0000] {settings.py:363} DEBUG - Disposing DB connection pool (PID 436)
[2025-06-17T02:33:11.863+0000] {settings.py:250} DEBUG - Setting up DB connection pool (PID 436)
[2025-06-17T02:33:11.878+0000] {settings.py:298} DEBUG - settings.prepare_engine_args(): Using NullPool
[2025-06-17T02:33:12.064+0000] {taskinstance.py:1042} DEBUG - previous_execution_date was called
[2025-06-17T02:33:12.093+0000] {taskinstance.py:1845} DEBUG - Clearing XCom data
[2025-06-17T02:33:12.167+0000] {retries.py:91} DEBUG - Running RenderedTaskInstanceFields.write with retries. Try 1 of 3
[2025-06-17T02:33:12.262+0000] {retries.py:91} DEBUG - Running RenderedTaskInstanceFields._do_delete_old_records with retries. Try 1 of 3
[2025-06-17T02:33:12.302+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='globalsuperstore' AIRFLOW_CTX_TASK_ID='transform.transform_dim_locations' AIRFLOW_CTX_EXECUTION_DATE='2025-06-16T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-06-16T00:00:00+00:00'
[2025-06-17T02:33:12.313+0000] {__init__.py:115} DEBUG - Preparing lineage inlets and outlets
[2025-06-17T02:33:12.316+0000] {__init__.py:154} DEBUG - inlets: [], outlets: []
[2025-06-17T02:33:12.318+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-17T02:33:12.410+0000] {base.py:84} INFO - Using connection ID 'postgres' for task execution.
[2025-06-17T02:33:12.450+0000] {base.py:84} INFO - Using connection ID 'postgres' for task execution.
[2025-06-17T02:33:12.476+0000] {base.py:84} INFO - Using connection ID 'postgres' for task execution.
[2025-06-17T02:33:12.501+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/***/providers/common/sql/hooks/sql.py:263 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2025-06-17T02:33:15.822+0000] {logging_mixin.py:188} INFO - ✔ Đã lưu dữ liệu vào warehouse.dim_location (3777 dòng)
[2025-06-17T02:33:15.827+0000] {logging_mixin.py:188} INFO - ✔ Đã transform và lưu dữ liệu vào warehouse.dim_location
[2025-06-17T02:33:15.900+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-06-17T02:33:15.910+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-17T02:33:15.915+0000] {__init__.py:77} DEBUG - Lineage called with inlets: [], outlets: []
[2025-06-17T02:33:15.955+0000] {taskinstance.py:584} DEBUG - Clearing next_method and next_kwargs.
[2025-06-17T02:33:15.966+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=globalsuperstore, task_id=transform.transform_dim_locations, run_id=scheduled__2025-06-16T00:00:00+00:00, execution_date=20250616T000000, start_date=20250617T023311, end_date=20250617T023315
[2025-06-17T02:33:15.972+0000] {taskinstance.py:562} DEBUG - Task Duration set to 4.617711
[2025-06-17T02:33:16.045+0000] {cli_action_loggers.py:88} DEBUG - Calling callbacks: []
[2025-06-17T02:33:16.127+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-06-17T02:33:16.189+0000] {dagrun.py:931} DEBUG - number of tis tasks for <DagRun globalsuperstore @ 2025-06-16 00:00:00+00:00: scheduled__2025-06-16T00:00:00+00:00, state:running, queued_at: 2025-06-17 02:32:39.844346+00:00. externally triggered: False>: 6 task(s)
[2025-06-17T02:33:16.193+0000] {dagrun.py:952} DEBUG - number of scheduleable tasks for <DagRun globalsuperstore @ 2025-06-16 00:00:00+00:00: scheduled__2025-06-16T00:00:00+00:00, state:running, queued_at: 2025-06-17 02:32:39.844346+00:00. externally triggered: False>: 0 task(s)
[2025-06-17T02:33:16.202+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-17T02:33:16.210+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-06-17T02:58:36.369+0000] {taskinstance.py:1042} DEBUG - previous_execution_date was called
[2025-06-17T02:58:36.432+0000] {__init__.py:54} DEBUG - Loading core task runner: StandardTaskRunner
[2025-06-17T02:58:36.476+0000] {taskinstance.py:1042} DEBUG - previous_execution_date was called
[2025-06-17T02:58:36.490+0000] {base_task_runner.py:73} DEBUG - Planning to run as the  user
[2025-06-17T02:58:36.542+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-17T02:58:36.670+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.transform.transform_dim_locations scheduled__2025-06-16T00:00:00+00:00 [queued]> dependency 'Task Instance State' PASSED: True, Task state queued was valid.
[2025-06-17T02:58:36.671+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.transform.transform_dim_locations scheduled__2025-06-16T00:00:00+00:00 [queued]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2025-06-17T02:58:36.672+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.transform.transform_dim_locations scheduled__2025-06-16T00:00:00+00:00 [queued]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2025-06-17T02:58:36.673+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.transform.transform_dim_locations scheduled__2025-06-16T00:00:00+00:00 [queued]> dependency 'Task Instance Not Running' PASSED: True, Task is not in running state.
[2025-06-17T02:58:36.684+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: globalsuperstore.transform.transform_dim_locations scheduled__2025-06-16T00:00:00+00:00 [queued]>
[2025-06-17T02:58:36.686+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.transform.transform_dim_locations scheduled__2025-06-16T00:00:00+00:00 [queued]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2025-06-17T02:58:36.693+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.transform.transform_dim_locations scheduled__2025-06-16T00:00:00+00:00 [queued]> dependency 'Pool Slots Available' PASSED: True, There are enough open slots in default_pool to execute the task
[2025-06-17T02:58:36.695+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.transform.transform_dim_locations scheduled__2025-06-16T00:00:00+00:00 [queued]> dependency 'Task Concurrency' PASSED: True, Task concurrency is not set.
[2025-06-17T02:58:36.695+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.transform.transform_dim_locations scheduled__2025-06-16T00:00:00+00:00 [queued]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2025-06-17T02:58:36.704+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: globalsuperstore.transform.transform_dim_locations scheduled__2025-06-16T00:00:00+00:00 [queued]>
[2025-06-17T02:58:36.705+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-06-17T02:58:36.732+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transform.transform_dim_locations> on 2025-06-16 00:00:00+00:00
[2025-06-17T02:58:36.753+0000] {standard_task_runner.py:63} INFO - Started process 335 to run task
[2025-06-17T02:58:36.757+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'globalsuperstore', 'transform.transform_dim_locations', 'scheduled__2025-06-16T00:00:00+00:00', '--job-id', '472', '--raw', '--subdir', 'DAGS_FOLDER/global_superstore_dw_etl.py', '--cfg-path', '/tmp/tmpc9wjogj4']
[2025-06-17T02:58:36.759+0000] {standard_task_runner.py:91} INFO - Job 472: Subtask transform.transform_dim_locations
[2025-06-17T02:58:36.766+0000] {cli_action_loggers.py:70} DEBUG - Calling callbacks: [<function default_action_log at 0x7f4b9ba99750>]
[2025-06-17T02:58:36.871+0000] {taskinstance.py:1042} DEBUG - previous_execution_date was called
[2025-06-17T02:58:36.884+0000] {task_command.py:426} INFO - Running <TaskInstance: globalsuperstore.transform.transform_dim_locations scheduled__2025-06-16T00:00:00+00:00 [running]> on host 9b7c60adfed6
[2025-06-17T02:58:36.887+0000] {settings.py:363} DEBUG - Disposing DB connection pool (PID 335)
[2025-06-17T02:58:36.888+0000] {settings.py:250} DEBUG - Setting up DB connection pool (PID 335)
[2025-06-17T02:58:36.889+0000] {settings.py:298} DEBUG - settings.prepare_engine_args(): Using NullPool
[2025-06-17T02:58:36.942+0000] {taskinstance.py:1042} DEBUG - previous_execution_date was called
[2025-06-17T02:58:36.945+0000] {taskinstance.py:1845} DEBUG - Clearing XCom data
[2025-06-17T02:58:36.994+0000] {retries.py:91} DEBUG - Running RenderedTaskInstanceFields.write with retries. Try 1 of 3
[2025-06-17T02:58:37.065+0000] {retries.py:91} DEBUG - Running RenderedTaskInstanceFields._do_delete_old_records with retries. Try 1 of 3
[2025-06-17T02:58:37.107+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='globalsuperstore' AIRFLOW_CTX_TASK_ID='transform.transform_dim_locations' AIRFLOW_CTX_EXECUTION_DATE='2025-06-16T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-06-16T00:00:00+00:00'
[2025-06-17T02:58:37.127+0000] {__init__.py:115} DEBUG - Preparing lineage inlets and outlets
[2025-06-17T02:58:37.129+0000] {__init__.py:154} DEBUG - inlets: [], outlets: []
[2025-06-17T02:58:37.132+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-17T02:58:37.241+0000] {base.py:84} INFO - Using connection ID 'postgres' for task execution.
[2025-06-17T02:58:37.256+0000] {base.py:84} INFO - Using connection ID 'postgres' for task execution.
[2025-06-17T02:58:37.288+0000] {sql.py:427} DEBUG - Executing following statements against DB: ['TRUNCATE TABLE "warehouse"."fact_sales" RESTART IDENTITY CASCADE']
[2025-06-17T02:58:37.310+0000] {base.py:84} INFO - Using connection ID 'postgres' for task execution.
[2025-06-17T02:58:37.317+0000] {sql.py:487} INFO - Running statement: TRUNCATE TABLE "warehouse"."fact_sales" RESTART IDENTITY CASCADE, parameters: None
[2025-06-17T02:58:37.414+0000] {sql.py:427} DEBUG - Executing following statements against DB: ['TRUNCATE TABLE "warehouse"."dim_location" RESTART IDENTITY CASCADE']
[2025-06-17T02:58:37.423+0000] {base.py:84} INFO - Using connection ID 'postgres' for task execution.
[2025-06-17T02:58:37.428+0000] {sql.py:487} INFO - Running statement: TRUNCATE TABLE "warehouse"."dim_location" RESTART IDENTITY CASCADE, parameters: None
[2025-06-17T02:58:37.520+0000] {base.py:84} INFO - Using connection ID 'postgres' for task execution.
[2025-06-17T02:58:37.540+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/***/providers/common/sql/hooks/sql.py:263 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2025-06-17T02:58:39.299+0000] {logging_mixin.py:188} INFO - ✔ Đã lưu dữ liệu vào warehouse.dim_location (3777 dòng)
[2025-06-17T02:58:39.300+0000] {logging_mixin.py:188} INFO - ✔ Đã transform và lưu dữ liệu vào warehouse.dim_location
[2025-06-17T02:58:39.319+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-06-17T02:58:39.323+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-17T02:58:39.325+0000] {__init__.py:77} DEBUG - Lineage called with inlets: [], outlets: []
[2025-06-17T02:58:39.335+0000] {taskinstance.py:584} DEBUG - Clearing next_method and next_kwargs.
[2025-06-17T02:58:39.336+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=globalsuperstore, task_id=transform.transform_dim_locations, run_id=scheduled__2025-06-16T00:00:00+00:00, execution_date=20250616T000000, start_date=20250617T025836, end_date=20250617T025839
[2025-06-17T02:58:39.336+0000] {taskinstance.py:562} DEBUG - Task Duration set to 2.649446
[2025-06-17T02:58:39.347+0000] {cli_action_loggers.py:88} DEBUG - Calling callbacks: []
[2025-06-17T02:58:39.393+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-06-17T02:58:39.420+0000] {dagrun.py:931} DEBUG - number of tis tasks for <DagRun globalsuperstore @ 2025-06-16 00:00:00+00:00: scheduled__2025-06-16T00:00:00+00:00, state:running, queued_at: 2025-06-17 02:58:05.858281+00:00. externally triggered: False>: 6 task(s)
[2025-06-17T02:58:39.421+0000] {dagrun.py:952} DEBUG - number of scheduleable tasks for <DagRun globalsuperstore @ 2025-06-16 00:00:00+00:00: scheduled__2025-06-16T00:00:00+00:00, state:running, queued_at: 2025-06-17 02:58:05.858281+00:00. externally triggered: False>: 1 task(s)
[2025-06-17T02:58:39.422+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.load.transform_fact_sales scheduled__2025-06-16T00:00:00+00:00 [None]> dependency 'Trigger Rule' PASSED: False, Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 1 non-success(es). upstream_states=_UpstreamTIStates(success=4, skipped=0, failed=0, upstream_failed=0, removed=0, done=4, success_setup=0, skipped_setup=0), upstream_task_ids={'transform.transform_dim_locations', 'transform.transform_dim_shipmode', 'transform.transform_dim_customers', 'transform.transform_dim_date', 'transform.transform_dim_products'}
[2025-06-17T02:58:39.423+0000] {taskinstance.py:2066} DEBUG - Dependencies not met for <TaskInstance: globalsuperstore.load.transform_fact_sales scheduled__2025-06-16T00:00:00+00:00 [None]>, dependency 'Trigger Rule' FAILED: Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 1 non-success(es). upstream_states=_UpstreamTIStates(success=4, skipped=0, failed=0, upstream_failed=0, removed=0, done=4, success_setup=0, skipped_setup=0), upstream_task_ids={'transform.transform_dim_locations', 'transform.transform_dim_shipmode', 'transform.transform_dim_customers', 'transform.transform_dim_date', 'transform.transform_dim_products'}
[2025-06-17T02:58:39.424+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.load.transform_fact_sales scheduled__2025-06-16T00:00:00+00:00 [None]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2025-06-17T02:58:39.424+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.load.transform_fact_sales scheduled__2025-06-16T00:00:00+00:00 [None]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2025-06-17T02:58:39.432+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-17T02:58:39.435+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
