[2025-06-15T08:46:14.759+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-15T08:46:15.017+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: globalsuperstore.transform.transform_dim_customers scheduled__2024-12-11T00:00:00+00:00 [queued]>
[2025-06-15T08:46:15.062+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: globalsuperstore.transform.transform_dim_customers scheduled__2024-12-11T00:00:00+00:00 [queued]>
[2025-06-15T08:46:15.064+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-06-15T08:46:15.105+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transform.transform_dim_customers> on 2024-12-11 00:00:00+00:00
[2025-06-15T08:46:15.139+0000] {standard_task_runner.py:63} INFO - Started process 1453 to run task
[2025-06-15T08:46:15.157+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'globalsuperstore', 'transform.transform_dim_customers', 'scheduled__2024-12-11T00:00:00+00:00', '--job-id', '170', '--raw', '--subdir', 'DAGS_FOLDER/global_superstore_dw_etl.py', '--cfg-path', '/tmp/tmp0kaqeep4']
[2025-06-15T08:46:15.177+0000] {standard_task_runner.py:91} INFO - Job 170: Subtask transform.transform_dim_customers
[2025-06-15T08:46:15.447+0000] {task_command.py:426} INFO - Running <TaskInstance: globalsuperstore.transform.transform_dim_customers scheduled__2024-12-11T00:00:00+00:00 [running]> on host f3cca4675eb8
[2025-06-15T08:46:15.773+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='globalsuperstore' AIRFLOW_CTX_TASK_ID='transform.transform_dim_customers' AIRFLOW_CTX_EXECUTION_DATE='2024-12-11T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-11T00:00:00+00:00'
[2025-06-15T08:46:15.779+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-15T08:46:15.894+0000] {base.py:84} INFO - Using connection ID 'postgres' for task execution.
[2025-06-15T08:46:15.929+0000] {base.py:84} INFO - Using connection ID 'postgres' for task execution.
[2025-06-15T08:46:15.953+0000] {base.py:84} INFO - Using connection ID 'postgres' for task execution.
[2025-06-15T08:46:16.081+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/***/providers/common/sql/hooks/sql.py:263 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2025-06-15T08:46:22.993+0000] {logging_mixin.py:188} INFO - ✔ Đã transform và lưu dữ liệu vào warehouse.dim_customer
[2025-06-15T08:46:22.995+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-06-15T08:46:22.996+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-15T08:46:23.010+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=globalsuperstore, task_id=transform.transform_dim_customers, run_id=scheduled__2024-12-11T00:00:00+00:00, execution_date=20241211T000000, start_date=20250615T084615, end_date=20250615T084623
[2025-06-15T08:46:23.055+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-06-15T08:46:23.068+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
