[2025-06-14T03:08:09.808+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-14T03:08:09.904+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: GlobalSuperStore_dw_etl.transform.transform_dim_customers manual__2025-06-14T03:07:48.195161+00:00 [queued]>
[2025-06-14T03:08:09.917+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: GlobalSuperStore_dw_etl.transform.transform_dim_customers manual__2025-06-14T03:07:48.195161+00:00 [queued]>
[2025-06-14T03:08:09.917+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-06-14T03:08:09.931+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transform.transform_dim_customers> on 2025-06-14 03:07:48.195161+00:00
[2025-06-14T03:08:09.943+0000] {standard_task_runner.py:63} INFO - Started process 229 to run task
[2025-06-14T03:08:09.946+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'GlobalSuperStore_dw_etl', 'transform.transform_dim_customers', 'manual__2025-06-14T03:07:48.195161+00:00', '--job-id', '99', '--raw', '--subdir', 'DAGS_FOLDER/globalSuperstore.py', '--cfg-path', '/tmp/tmp6i_0nxrh']
[2025-06-14T03:08:09.949+0000] {standard_task_runner.py:91} INFO - Job 99: Subtask transform.transform_dim_customers
[2025-06-14T03:08:10.022+0000] {task_command.py:426} INFO - Running <TaskInstance: GlobalSuperStore_dw_etl.transform.transform_dim_customers manual__2025-06-14T03:07:48.195161+00:00 [running]> on host ce8c7e7a2a87
[2025-06-14T03:08:10.109+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='GlobalSuperStore_dw_etl' AIRFLOW_CTX_TASK_ID='transform.transform_dim_customers' AIRFLOW_CTX_EXECUTION_DATE='2025-06-14T03:07:48.195161+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-14T03:07:48.195161+00:00'
[2025-06-14T03:08:10.110+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-14T03:08:10.129+0000] {base.py:84} INFO - Using connection ID 'postgres' for task execution.
[2025-06-14T03:08:10.139+0000] {base.py:84} INFO - Using connection ID 'postgres' for task execution.
[2025-06-14T03:08:10.146+0000] {base.py:84} INFO - Using connection ID 'postgres' for task execution.
[2025-06-14T03:08:10.168+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/***/providers/common/sql/hooks/sql.py:263 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2025-06-14T03:08:10.175+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-14T03:08:10.177+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/io/sql.py", line 2018, in execute
    cur.execute(*args, **kwargs)
psycopg2.errors.UndefinedTable: relation "staging.stg_customer" does not exist
LINE 1: SELECT * FROM staging.stg_customer
                      ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/transform_dim_customers.py", line 14, in transform_dim_customers
    df = staging_operator.get_data_to_pd("SELECT * FROM staging.stg_customer")
  File "/opt/airflow/plugins/postgresql_operator.py", line 15, in get_data_to_pd
    return self.hook.get_pandas_df(sql)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/common/sql/hooks/sql.py", line 263, in get_pandas_df
    return psql.read_sql(sql, con=conn, params=parameters, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/io/sql.py", line 564, in read_sql
    return pandas_sql.read_query(
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/io/sql.py", line 2078, in read_query
    cursor = self.execute(*args)
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/io/sql.py", line 2030, in execute
    raise ex from exc
pandas.errors.DatabaseError: Execution failed on sql 'SELECT * FROM staging.stg_customer': relation "staging.stg_customer" does not exist
LINE 1: SELECT * FROM staging.stg_customer
                      ^

[2025-06-14T03:08:10.243+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=GlobalSuperStore_dw_etl, task_id=transform.transform_dim_customers, run_id=manual__2025-06-14T03:07:48.195161+00:00, execution_date=20250614T030748, start_date=20250614T030809, end_date=20250614T030810
[2025-06-14T03:08:10.263+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 99 for task transform.transform_dim_customers (Execution failed on sql 'SELECT * FROM staging.stg_customer': relation "staging.stg_customer" does not exist
LINE 1: SELECT * FROM staging.stg_customer
                      ^
; 229)
[2025-06-14T03:08:10.281+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-06-14T03:08:10.307+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-14T03:08:10.311+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
