[2025-06-16T15:48:46.546+0000] {taskinstance.py:1042} DEBUG - previous_execution_date was called
[2025-06-16T15:48:46.586+0000] {__init__.py:54} DEBUG - Loading core task runner: StandardTaskRunner
[2025-06-16T15:48:46.610+0000] {taskinstance.py:1042} DEBUG - previous_execution_date was called
[2025-06-16T15:48:46.624+0000] {base_task_runner.py:73} DEBUG - Planning to run as the  user
[2025-06-16T15:48:46.637+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-16T15:48:46.691+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.transform.transform_dim_date manual__2025-06-16T15:48:26.486110+00:00 [queued]> dependency 'Task Instance State' PASSED: True, Task state queued was valid.
[2025-06-16T15:48:46.692+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.transform.transform_dim_date manual__2025-06-16T15:48:26.486110+00:00 [queued]> dependency 'Task Instance Not Running' PASSED: True, Task is not in running state.
[2025-06-16T15:48:46.693+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.transform.transform_dim_date manual__2025-06-16T15:48:26.486110+00:00 [queued]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2025-06-16T15:48:46.694+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.transform.transform_dim_date manual__2025-06-16T15:48:26.486110+00:00 [queued]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2025-06-16T15:48:46.707+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: globalsuperstore.transform.transform_dim_date manual__2025-06-16T15:48:26.486110+00:00 [queued]>
[2025-06-16T15:48:46.718+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.transform.transform_dim_date manual__2025-06-16T15:48:26.486110+00:00 [queued]> dependency 'Pool Slots Available' PASSED: True, There are enough open slots in default_pool to execute the task
[2025-06-16T15:48:46.719+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.transform.transform_dim_date manual__2025-06-16T15:48:26.486110+00:00 [queued]> dependency 'Task Concurrency' PASSED: True, Task concurrency is not set.
[2025-06-16T15:48:46.720+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.transform.transform_dim_date manual__2025-06-16T15:48:26.486110+00:00 [queued]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2025-06-16T15:48:46.721+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.transform.transform_dim_date manual__2025-06-16T15:48:26.486110+00:00 [queued]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2025-06-16T15:48:46.730+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: globalsuperstore.transform.transform_dim_date manual__2025-06-16T15:48:26.486110+00:00 [queued]>
[2025-06-16T15:48:46.731+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-06-16T15:48:46.763+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transform.transform_dim_date> on 2025-06-16 15:48:26.486110+00:00
[2025-06-16T15:48:46.781+0000] {standard_task_runner.py:63} INFO - Started process 470 to run task
[2025-06-16T15:48:46.794+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'globalsuperstore', 'transform.transform_dim_date', 'manual__2025-06-16T15:48:26.486110+00:00', '--job-id', '126', '--raw', '--subdir', 'DAGS_FOLDER/global_superstore_dw_etl.py', '--cfg-path', '/tmp/tmpyud40qwc']
[2025-06-16T15:48:46.796+0000] {standard_task_runner.py:91} INFO - Job 126: Subtask transform.transform_dim_date
[2025-06-16T15:48:46.798+0000] {cli_action_loggers.py:70} DEBUG - Calling callbacks: [<function default_action_log at 0x7fa267925750>]
[2025-06-16T15:48:46.871+0000] {taskinstance.py:1042} DEBUG - previous_execution_date was called
[2025-06-16T15:48:46.880+0000] {task_command.py:426} INFO - Running <TaskInstance: globalsuperstore.transform.transform_dim_date manual__2025-06-16T15:48:26.486110+00:00 [running]> on host 9b7c60adfed6
[2025-06-16T15:48:46.881+0000] {settings.py:363} DEBUG - Disposing DB connection pool (PID 470)
[2025-06-16T15:48:46.882+0000] {settings.py:250} DEBUG - Setting up DB connection pool (PID 470)
[2025-06-16T15:48:46.883+0000] {settings.py:298} DEBUG - settings.prepare_engine_args(): Using NullPool
[2025-06-16T15:48:46.935+0000] {taskinstance.py:1042} DEBUG - previous_execution_date was called
[2025-06-16T15:48:46.939+0000] {taskinstance.py:1845} DEBUG - Clearing XCom data
[2025-06-16T15:48:46.959+0000] {retries.py:91} DEBUG - Running RenderedTaskInstanceFields.write with retries. Try 1 of 3
[2025-06-16T15:48:46.994+0000] {retries.py:91} DEBUG - Running RenderedTaskInstanceFields._do_delete_old_records with retries. Try 1 of 3
[2025-06-16T15:48:47.017+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='globalsuperstore' AIRFLOW_CTX_TASK_ID='transform.transform_dim_date' AIRFLOW_CTX_EXECUTION_DATE='2025-06-16T15:48:26.486110+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-16T15:48:26.486110+00:00'
[2025-06-16T15:48:47.018+0000] {__init__.py:115} DEBUG - Preparing lineage inlets and outlets
[2025-06-16T15:48:47.019+0000] {__init__.py:154} DEBUG - inlets: [], outlets: []
[2025-06-16T15:48:47.019+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-16T15:48:47.546+0000] {base.py:84} INFO - Using connection ID 'postgres' for task execution.
[2025-06-16T15:48:47.562+0000] {base.py:84} INFO - Using connection ID 'postgres' for task execution.
[2025-06-16T15:48:47.585+0000] {base.py:84} INFO - Using connection ID 'postgres' for task execution.
[2025-06-16T15:48:47.600+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/***/providers/common/sql/hooks/sql.py:263 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2025-06-16T15:48:47.662+0000] {logging_mixin.py:188} INFO - ✔ Đã transform và lưu dữ liệu vào warehouse.dim_date
[2025-06-16T15:48:47.663+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-06-16T15:48:47.665+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-16T15:48:47.666+0000] {__init__.py:77} DEBUG - Lineage called with inlets: [], outlets: []
[2025-06-16T15:48:47.682+0000] {taskinstance.py:584} DEBUG - Clearing next_method and next_kwargs.
[2025-06-16T15:48:47.684+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=globalsuperstore, task_id=transform.transform_dim_date, run_id=manual__2025-06-16T15:48:26.486110+00:00, execution_date=20250616T154826, start_date=20250616T154846, end_date=20250616T154847
[2025-06-16T15:48:47.686+0000] {taskinstance.py:562} DEBUG - Task Duration set to 0.975167
[2025-06-16T15:48:47.708+0000] {cli_action_loggers.py:88} DEBUG - Calling callbacks: []
[2025-06-16T15:48:47.765+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-06-16T15:48:47.778+0000] {taskinstance.py:3461} DEBUG - Skip locked rows, rollback
[2025-06-16T15:48:47.780+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
