[2025-06-16T16:59:34.855+0000] {taskinstance.py:1042} DEBUG - previous_execution_date was called
[2025-06-16T16:59:34.894+0000] {__init__.py:54} DEBUG - Loading core task runner: StandardTaskRunner
[2025-06-16T16:59:34.910+0000] {taskinstance.py:1042} DEBUG - previous_execution_date was called
[2025-06-16T16:59:34.918+0000] {base_task_runner.py:73} DEBUG - Planning to run as the  user
[2025-06-16T16:59:34.930+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-16T16:59:35.011+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.transform.transform_dim_date manual__2025-06-16T16:59:08.156755+00:00 [queued]> dependency 'Task Instance Not Running' PASSED: True, Task is not in running state.
[2025-06-16T16:59:35.012+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.transform.transform_dim_date manual__2025-06-16T16:59:08.156755+00:00 [queued]> dependency 'Task Instance State' PASSED: True, Task state queued was valid.
[2025-06-16T16:59:35.012+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.transform.transform_dim_date manual__2025-06-16T16:59:08.156755+00:00 [queued]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2025-06-16T16:59:35.013+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.transform.transform_dim_date manual__2025-06-16T16:59:08.156755+00:00 [queued]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2025-06-16T16:59:35.013+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: globalsuperstore.transform.transform_dim_date manual__2025-06-16T16:59:08.156755+00:00 [queued]>
[2025-06-16T16:59:35.021+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.transform.transform_dim_date manual__2025-06-16T16:59:08.156755+00:00 [queued]> dependency 'Pool Slots Available' PASSED: True, There are enough open slots in default_pool to execute the task
[2025-06-16T16:59:35.022+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.transform.transform_dim_date manual__2025-06-16T16:59:08.156755+00:00 [queued]> dependency 'Task Concurrency' PASSED: True, Task concurrency is not set.
[2025-06-16T16:59:35.026+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.transform.transform_dim_date manual__2025-06-16T16:59:08.156755+00:00 [queued]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2025-06-16T16:59:35.027+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.transform.transform_dim_date manual__2025-06-16T16:59:08.156755+00:00 [queued]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2025-06-16T16:59:35.033+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: globalsuperstore.transform.transform_dim_date manual__2025-06-16T16:59:08.156755+00:00 [queued]>
[2025-06-16T16:59:35.034+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-06-16T16:59:35.054+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transform.transform_dim_date> on 2025-06-16 16:59:08.156755+00:00
[2025-06-16T16:59:35.070+0000] {standard_task_runner.py:63} INFO - Started process 339 to run task
[2025-06-16T16:59:35.076+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'globalsuperstore', 'transform.transform_dim_date', 'manual__2025-06-16T16:59:08.156755+00:00', '--job-id', '256', '--raw', '--subdir', 'DAGS_FOLDER/global_superstore_dw_etl.py', '--cfg-path', '/tmp/tmpc57jd2ve']
[2025-06-16T16:59:35.078+0000] {standard_task_runner.py:91} INFO - Job 256: Subtask transform.transform_dim_date
[2025-06-16T16:59:35.079+0000] {cli_action_loggers.py:70} DEBUG - Calling callbacks: [<function default_action_log at 0x7fb4a9929750>]
[2025-06-16T16:59:35.144+0000] {taskinstance.py:1042} DEBUG - previous_execution_date was called
[2025-06-16T16:59:35.149+0000] {task_command.py:426} INFO - Running <TaskInstance: globalsuperstore.transform.transform_dim_date manual__2025-06-16T16:59:08.156755+00:00 [running]> on host 9b7c60adfed6
[2025-06-16T16:59:35.150+0000] {settings.py:363} DEBUG - Disposing DB connection pool (PID 339)
[2025-06-16T16:59:35.150+0000] {settings.py:250} DEBUG - Setting up DB connection pool (PID 339)
[2025-06-16T16:59:35.151+0000] {settings.py:298} DEBUG - settings.prepare_engine_args(): Using NullPool
[2025-06-16T16:59:35.191+0000] {taskinstance.py:1042} DEBUG - previous_execution_date was called
[2025-06-16T16:59:35.193+0000] {taskinstance.py:1845} DEBUG - Clearing XCom data
[2025-06-16T16:59:35.214+0000] {retries.py:91} DEBUG - Running RenderedTaskInstanceFields.write with retries. Try 1 of 3
[2025-06-16T16:59:35.251+0000] {retries.py:91} DEBUG - Running RenderedTaskInstanceFields._do_delete_old_records with retries. Try 1 of 3
[2025-06-16T16:59:35.275+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='globalsuperstore' AIRFLOW_CTX_TASK_ID='transform.transform_dim_date' AIRFLOW_CTX_EXECUTION_DATE='2025-06-16T16:59:08.156755+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-16T16:59:08.156755+00:00'
[2025-06-16T16:59:35.278+0000] {__init__.py:115} DEBUG - Preparing lineage inlets and outlets
[2025-06-16T16:59:35.281+0000] {__init__.py:154} DEBUG - inlets: [], outlets: []
[2025-06-16T16:59:35.282+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-16T16:59:35.333+0000] {base.py:84} INFO - Using connection ID 'postgres' for task execution.
[2025-06-16T16:59:35.367+0000] {base.py:84} INFO - Using connection ID 'postgres' for task execution.
[2025-06-16T16:59:35.391+0000] {base.py:84} INFO - Using connection ID 'postgres' for task execution.
[2025-06-16T16:59:35.408+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/***/providers/common/sql/hooks/sql.py:263 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2025-06-16T16:59:36.143+0000] {logging_mixin.py:188} INFO - ✔ Đã lưu dữ liệu vào warehouse.dim_date (1428 dòng)
[2025-06-16T16:59:36.144+0000] {logging_mixin.py:188} INFO - ✔ Đã transform và lưu dữ liệu vào warehouse.dim_date
[2025-06-16T16:59:36.144+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-06-16T16:59:36.145+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-16T16:59:36.146+0000] {__init__.py:77} DEBUG - Lineage called with inlets: [], outlets: []
[2025-06-16T16:59:36.157+0000] {taskinstance.py:584} DEBUG - Clearing next_method and next_kwargs.
[2025-06-16T16:59:36.158+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=globalsuperstore, task_id=transform.transform_dim_date, run_id=manual__2025-06-16T16:59:08.156755+00:00, execution_date=20250616T165908, start_date=20250616T165935, end_date=20250616T165936
[2025-06-16T16:59:36.158+0000] {taskinstance.py:562} DEBUG - Task Duration set to 1.144084
[2025-06-16T16:59:36.174+0000] {cli_action_loggers.py:88} DEBUG - Calling callbacks: []
[2025-06-16T16:59:36.218+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-06-16T16:59:36.240+0000] {dagrun.py:931} DEBUG - number of tis tasks for <DagRun globalsuperstore @ 2025-06-16 16:59:08.156755+00:00: manual__2025-06-16T16:59:08.156755+00:00, state:running, queued_at: 2025-06-16 16:59:08.290676+00:00. externally triggered: True>: 6 task(s)
[2025-06-16T16:59:36.241+0000] {dagrun.py:952} DEBUG - number of scheduleable tasks for <DagRun globalsuperstore @ 2025-06-16 16:59:08.156755+00:00: manual__2025-06-16T16:59:08.156755+00:00, state:running, queued_at: 2025-06-16 16:59:08.290676+00:00. externally triggered: True>: 1 task(s)
[2025-06-16T16:59:36.242+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.load.transform_fact_sales manual__2025-06-16T16:59:08.156755+00:00 [None]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2025-06-16T16:59:36.243+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.load.transform_fact_sales manual__2025-06-16T16:59:08.156755+00:00 [None]> dependency 'Trigger Rule' PASSED: False, Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 2 non-success(es). upstream_states=_UpstreamTIStates(success=3, skipped=0, failed=0, upstream_failed=0, removed=0, done=3, success_setup=0, skipped_setup=0), upstream_task_ids={'transform.transform_dim_date', 'transform.transform_dim_locations', 'transform.transform_dim_customers', 'transform.transform_dim_shipmode', 'transform.transform_dim_products'}
[2025-06-16T16:59:36.243+0000] {taskinstance.py:2066} DEBUG - Dependencies not met for <TaskInstance: globalsuperstore.load.transform_fact_sales manual__2025-06-16T16:59:08.156755+00:00 [None]>, dependency 'Trigger Rule' FAILED: Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 2 non-success(es). upstream_states=_UpstreamTIStates(success=3, skipped=0, failed=0, upstream_failed=0, removed=0, done=3, success_setup=0, skipped_setup=0), upstream_task_ids={'transform.transform_dim_date', 'transform.transform_dim_locations', 'transform.transform_dim_customers', 'transform.transform_dim_shipmode', 'transform.transform_dim_products'}
[2025-06-16T16:59:36.243+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.load.transform_fact_sales manual__2025-06-16T16:59:08.156755+00:00 [None]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2025-06-16T16:59:36.248+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-16T16:59:36.250+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
