[2025-06-15T16:50:09.563+0000] {taskinstance.py:1042} DEBUG - previous_execution_date was called
[2025-06-15T16:50:09.600+0000] {__init__.py:54} DEBUG - Loading core task runner: StandardTaskRunner
[2025-06-15T16:50:09.630+0000] {taskinstance.py:1042} DEBUG - previous_execution_date was called
[2025-06-15T16:50:09.640+0000] {base_task_runner.py:73} DEBUG - Planning to run as the  user
[2025-06-15T16:50:09.701+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-15T16:50:10.131+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.extract.extract_and_load_to_staging manual__2025-06-15T16:50:05.830452+00:00 [queued]> dependency 'Trigger Rule' PASSED: True, The task instance did not have any upstream tasks.
[2025-06-15T16:50:10.135+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.extract.extract_and_load_to_staging manual__2025-06-15T16:50:05.830452+00:00 [queued]> dependency 'Task Instance Not Running' PASSED: True, Task is not in running state.
[2025-06-15T16:50:10.140+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.extract.extract_and_load_to_staging manual__2025-06-15T16:50:05.830452+00:00 [queued]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2025-06-15T16:50:10.161+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.extract.extract_and_load_to_staging manual__2025-06-15T16:50:05.830452+00:00 [queued]> dependency 'Task Instance State' PASSED: True, Task state queued was valid.
[2025-06-15T16:50:10.162+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.extract.extract_and_load_to_staging manual__2025-06-15T16:50:05.830452+00:00 [queued]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2025-06-15T16:50:10.163+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: globalsuperstore.extract.extract_and_load_to_staging manual__2025-06-15T16:50:05.830452+00:00 [queued]>
[2025-06-15T16:50:10.171+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.extract.extract_and_load_to_staging manual__2025-06-15T16:50:05.830452+00:00 [queued]> dependency 'Trigger Rule' PASSED: True, The task instance did not have any upstream tasks.
[2025-06-15T16:50:10.172+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.extract.extract_and_load_to_staging manual__2025-06-15T16:50:05.830452+00:00 [queued]> dependency 'Task Concurrency' PASSED: True, Task concurrency is not set.
[2025-06-15T16:50:10.184+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.extract.extract_and_load_to_staging manual__2025-06-15T16:50:05.830452+00:00 [queued]> dependency 'Pool Slots Available' PASSED: True, There are enough open slots in default_pool to execute the task
[2025-06-15T16:50:10.184+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.extract.extract_and_load_to_staging manual__2025-06-15T16:50:05.830452+00:00 [queued]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2025-06-15T16:50:10.190+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.extract.extract_and_load_to_staging manual__2025-06-15T16:50:05.830452+00:00 [queued]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2025-06-15T16:50:10.191+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: globalsuperstore.extract.extract_and_load_to_staging manual__2025-06-15T16:50:05.830452+00:00 [queued]>
[2025-06-15T16:50:10.192+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-06-15T16:50:10.254+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract.extract_and_load_to_staging> on 2025-06-15 16:50:05.830452+00:00
[2025-06-15T16:50:10.295+0000] {standard_task_runner.py:63} INFO - Started process 558 to run task
[2025-06-15T16:50:10.308+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'globalsuperstore', 'extract.extract_and_load_to_staging', 'manual__2025-06-15T16:50:05.830452+00:00', '--job-id', '91', '--raw', '--subdir', 'DAGS_FOLDER/global_superstore_dw_etl.py', '--cfg-path', '/tmp/tmpidwz6eyx']
[2025-06-15T16:50:10.311+0000] {standard_task_runner.py:91} INFO - Job 91: Subtask extract.extract_and_load_to_staging
[2025-06-15T16:50:10.314+0000] {cli_action_loggers.py:70} DEBUG - Calling callbacks: [<function default_action_log at 0x7fd327729750>]
[2025-06-15T16:50:10.423+0000] {taskinstance.py:1042} DEBUG - previous_execution_date was called
[2025-06-15T16:50:10.441+0000] {task_command.py:426} INFO - Running <TaskInstance: globalsuperstore.extract.extract_and_load_to_staging manual__2025-06-15T16:50:05.830452+00:00 [running]> on host a40e01b9e58f
[2025-06-15T16:50:10.442+0000] {settings.py:363} DEBUG - Disposing DB connection pool (PID 558)
[2025-06-15T16:50:10.443+0000] {settings.py:250} DEBUG - Setting up DB connection pool (PID 558)
[2025-06-15T16:50:10.444+0000] {settings.py:298} DEBUG - settings.prepare_engine_args(): Using NullPool
[2025-06-15T16:50:10.537+0000] {taskinstance.py:1042} DEBUG - previous_execution_date was called
[2025-06-15T16:50:10.555+0000] {taskinstance.py:1845} DEBUG - Clearing XCom data
[2025-06-15T16:50:10.675+0000] {retries.py:91} DEBUG - Running RenderedTaskInstanceFields.write with retries. Try 1 of 3
[2025-06-15T16:50:10.744+0000] {retries.py:91} DEBUG - Running RenderedTaskInstanceFields._do_delete_old_records with retries. Try 1 of 3
[2025-06-15T16:50:10.800+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='globalsuperstore' AIRFLOW_CTX_TASK_ID='extract.extract_and_load_to_staging' AIRFLOW_CTX_EXECUTION_DATE='2025-06-15T16:50:05.830452+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-15T16:50:05.830452+00:00'
[2025-06-15T16:50:10.802+0000] {__init__.py:115} DEBUG - Preparing lineage inlets and outlets
[2025-06-15T16:50:10.804+0000] {__init__.py:154} DEBUG - inlets: [], outlets: []
[2025-06-15T16:50:10.806+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-15T16:50:10.959+0000] {base.py:84} INFO - Using connection ID 'postgres' for task execution.
[2025-06-15T16:50:10.984+0000] {base.py:84} INFO - Using connection ID 'mysql' for task execution.
[2025-06-15T16:50:11.582+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/***/providers/common/sql/hooks/sql.py:263 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2025-06-15T16:50:12.912+0000] {logging_mixin.py:188} INFO - ✔ Đã load Category → staging.stg_Category
[2025-06-15T16:50:12.936+0000] {base.py:84} INFO - Using connection ID 'mysql' for task execution.
[2025-06-15T16:50:12.964+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/***/providers/common/sql/hooks/sql.py:263 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2025-06-15T16:50:15.332+0000] {retries.py:91} DEBUG - Running Job._fetch_from_db with retries. Try 1 of 3
[2025-06-15T16:50:15.367+0000] {retries.py:91} DEBUG - Running Job._update_heartbeat with retries. Try 1 of 3
[2025-06-15T16:50:15.401+0000] {job.py:214} DEBUG - [heartbeat]
[2025-06-15T16:50:18.047+0000] {logging_mixin.py:188} INFO - ✔ Đã load Customer → staging.stg_Customer
[2025-06-15T16:50:18.061+0000] {base.py:84} INFO - Using connection ID 'mysql' for task execution.
[2025-06-15T16:50:18.069+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/***/providers/common/sql/hooks/sql.py:263 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2025-06-15T16:50:20.435+0000] {retries.py:91} DEBUG - Running Job._fetch_from_db with retries. Try 1 of 3
[2025-06-15T16:50:20.441+0000] {retries.py:91} DEBUG - Running Job._update_heartbeat with retries. Try 1 of 3
[2025-06-15T16:50:20.474+0000] {job.py:214} DEBUG - [heartbeat]
[2025-06-15T16:50:25.483+0000] {retries.py:91} DEBUG - Running Job._fetch_from_db with retries. Try 1 of 3
[2025-06-15T16:50:25.491+0000] {retries.py:91} DEBUG - Running Job._update_heartbeat with retries. Try 1 of 3
[2025-06-15T16:50:25.501+0000] {job.py:214} DEBUG - [heartbeat]
[2025-06-15T16:50:30.530+0000] {retries.py:91} DEBUG - Running Job._fetch_from_db with retries. Try 1 of 3
[2025-06-15T16:50:30.542+0000] {retries.py:91} DEBUG - Running Job._update_heartbeat with retries. Try 1 of 3
[2025-06-15T16:50:30.557+0000] {job.py:214} DEBUG - [heartbeat]
[2025-06-15T16:50:30.875+0000] {logging_mixin.py:188} INFO - ✔ Đã load Order_Details → staging.stg_Order_Details
[2025-06-15T16:50:30.885+0000] {base.py:84} INFO - Using connection ID 'mysql' for task execution.
[2025-06-15T16:50:30.891+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/***/providers/common/sql/hooks/sql.py:263 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2025-06-15T16:50:35.596+0000] {retries.py:91} DEBUG - Running Job._fetch_from_db with retries. Try 1 of 3
[2025-06-15T16:50:35.607+0000] {retries.py:91} DEBUG - Running Job._update_heartbeat with retries. Try 1 of 3
[2025-06-15T16:50:35.620+0000] {job.py:214} DEBUG - [heartbeat]
[2025-06-15T16:50:36.658+0000] {logging_mixin.py:188} INFO - ✔ Đã load Orders → staging.stg_Orders
[2025-06-15T16:50:36.668+0000] {base.py:84} INFO - Using connection ID 'mysql' for task execution.
[2025-06-15T16:50:36.676+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/***/providers/common/sql/hooks/sql.py:263 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2025-06-15T16:50:37.667+0000] {logging_mixin.py:188} INFO - ✔ Đã load Product → staging.stg_Product
[2025-06-15T16:50:37.675+0000] {base.py:84} INFO - Using connection ID 'mysql' for task execution.
[2025-06-15T16:50:37.679+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/***/providers/common/sql/hooks/sql.py:263 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2025-06-15T16:50:37.719+0000] {logging_mixin.py:188} INFO - ✔ Đã load Sub_Category → staging.stg_Sub_Category
[2025-06-15T16:50:37.719+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-06-15T16:50:37.720+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-15T16:50:37.721+0000] {__init__.py:77} DEBUG - Lineage called with inlets: [], outlets: []
[2025-06-15T16:50:37.732+0000] {taskinstance.py:584} DEBUG - Clearing next_method and next_kwargs.
[2025-06-15T16:50:37.733+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=globalsuperstore, task_id=extract.extract_and_load_to_staging, run_id=manual__2025-06-15T16:50:05.830452+00:00, execution_date=20250615T165005, start_date=20250615T165010, end_date=20250615T165037
[2025-06-15T16:50:37.734+0000] {taskinstance.py:562} DEBUG - Task Duration set to 27.569668
[2025-06-15T16:50:37.746+0000] {cli_action_loggers.py:88} DEBUG - Calling callbacks: []
[2025-06-15T16:50:37.809+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-06-15T16:50:37.838+0000] {dagrun.py:931} DEBUG - number of tis tasks for <DagRun globalsuperstore @ 2025-06-15 16:50:05.830452+00:00: manual__2025-06-15T16:50:05.830452+00:00, state:running, queued_at: 2025-06-15 16:50:06.195501+00:00. externally triggered: True>: 7 task(s)
[2025-06-15T16:50:37.839+0000] {dagrun.py:952} DEBUG - number of scheduleable tasks for <DagRun globalsuperstore @ 2025-06-15 16:50:05.830452+00:00: manual__2025-06-15T16:50:05.830452+00:00, state:running, queued_at: 2025-06-15 16:50:06.195501+00:00. externally triggered: True>: 6 task(s)
[2025-06-15T16:50:37.840+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.transform.transform_dim_customers manual__2025-06-15T16:50:05.830452+00:00 [None]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2025-06-15T16:50:37.841+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.transform.transform_dim_customers manual__2025-06-15T16:50:05.830452+00:00 [None]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2025-06-15T16:50:37.842+0000] {taskinstance.py:2076} DEBUG - Dependencies all met for dep_context=None ti=<TaskInstance: globalsuperstore.transform.transform_dim_customers manual__2025-06-15T16:50:05.830452+00:00 [None]>
[2025-06-15T16:50:37.843+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.transform.transform_dim_products manual__2025-06-15T16:50:05.830452+00:00 [None]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2025-06-15T16:50:37.843+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.transform.transform_dim_products manual__2025-06-15T16:50:05.830452+00:00 [None]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2025-06-15T16:50:37.843+0000] {taskinstance.py:2076} DEBUG - Dependencies all met for dep_context=None ti=<TaskInstance: globalsuperstore.transform.transform_dim_products manual__2025-06-15T16:50:05.830452+00:00 [None]>
[2025-06-15T16:50:37.844+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.transform.transform_dim_locations manual__2025-06-15T16:50:05.830452+00:00 [None]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2025-06-15T16:50:37.844+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.transform.transform_dim_locations manual__2025-06-15T16:50:05.830452+00:00 [None]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2025-06-15T16:50:37.845+0000] {taskinstance.py:2076} DEBUG - Dependencies all met for dep_context=None ti=<TaskInstance: globalsuperstore.transform.transform_dim_locations manual__2025-06-15T16:50:05.830452+00:00 [None]>
[2025-06-15T16:50:37.845+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.transform.transform_dim_shipmode manual__2025-06-15T16:50:05.830452+00:00 [None]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2025-06-15T16:50:37.845+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.transform.transform_dim_shipmode manual__2025-06-15T16:50:05.830452+00:00 [None]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2025-06-15T16:50:37.846+0000] {taskinstance.py:2076} DEBUG - Dependencies all met for dep_context=None ti=<TaskInstance: globalsuperstore.transform.transform_dim_shipmode manual__2025-06-15T16:50:05.830452+00:00 [None]>
[2025-06-15T16:50:37.846+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.transform.transform_dim_date manual__2025-06-15T16:50:05.830452+00:00 [None]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2025-06-15T16:50:37.847+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.transform.transform_dim_date manual__2025-06-15T16:50:05.830452+00:00 [None]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2025-06-15T16:50:37.847+0000] {taskinstance.py:2076} DEBUG - Dependencies all met for dep_context=None ti=<TaskInstance: globalsuperstore.transform.transform_dim_date manual__2025-06-15T16:50:05.830452+00:00 [None]>
[2025-06-15T16:50:37.848+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.load.transform_fact_sales manual__2025-06-15T16:50:05.830452+00:00 [None]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2025-06-15T16:50:37.848+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.load.transform_fact_sales manual__2025-06-15T16:50:05.830452+00:00 [None]> dependency 'Trigger Rule' PASSED: False, Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 5 non-success(es). upstream_states=_UpstreamTIStates(success=0, skipped=0, failed=0, upstream_failed=0, removed=0, done=0, success_setup=0, skipped_setup=0), upstream_task_ids={'transform.transform_dim_customers', 'transform.transform_dim_shipmode', 'transform.transform_dim_date', 'transform.transform_dim_locations', 'transform.transform_dim_products'}
[2025-06-15T16:50:37.849+0000] {taskinstance.py:2066} DEBUG - Dependencies not met for <TaskInstance: globalsuperstore.load.transform_fact_sales manual__2025-06-15T16:50:05.830452+00:00 [None]>, dependency 'Trigger Rule' FAILED: Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 5 non-success(es). upstream_states=_UpstreamTIStates(success=0, skipped=0, failed=0, upstream_failed=0, removed=0, done=0, success_setup=0, skipped_setup=0), upstream_task_ids={'transform.transform_dim_customers', 'transform.transform_dim_shipmode', 'transform.transform_dim_date', 'transform.transform_dim_locations', 'transform.transform_dim_products'}
[2025-06-15T16:50:37.849+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.load.transform_fact_sales manual__2025-06-15T16:50:05.830452+00:00 [None]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2025-06-15T16:50:37.858+0000] {taskinstance.py:3503} INFO - 5 downstream tasks scheduled from follow-on schedule check
[2025-06-15T16:50:37.860+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
