[2025-06-17T01:35:56.783+0000] {taskinstance.py:1042} DEBUG - previous_execution_date was called
[2025-06-17T01:35:56.808+0000] {__init__.py:54} DEBUG - Loading core task runner: StandardTaskRunner
[2025-06-17T01:35:56.829+0000] {taskinstance.py:1042} DEBUG - previous_execution_date was called
[2025-06-17T01:35:56.834+0000] {base_task_runner.py:73} DEBUG - Planning to run as the  user
[2025-06-17T01:35:56.905+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-17T01:35:57.299+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.extract.extract_and_load_to_staging manual__2025-06-17T01:35:53.616298+00:00 [queued]> dependency 'Trigger Rule' PASSED: True, The task instance did not have any upstream tasks.
[2025-06-17T01:35:57.302+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.extract.extract_and_load_to_staging manual__2025-06-17T01:35:53.616298+00:00 [queued]> dependency 'Task Instance State' PASSED: True, Task state queued was valid.
[2025-06-17T01:35:57.325+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.extract.extract_and_load_to_staging manual__2025-06-17T01:35:53.616298+00:00 [queued]> dependency 'Task Instance Not Running' PASSED: True, Task is not in running state.
[2025-06-17T01:35:57.327+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.extract.extract_and_load_to_staging manual__2025-06-17T01:35:53.616298+00:00 [queued]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2025-06-17T01:35:57.329+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.extract.extract_and_load_to_staging manual__2025-06-17T01:35:53.616298+00:00 [queued]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2025-06-17T01:35:57.330+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: globalsuperstore.extract.extract_and_load_to_staging manual__2025-06-17T01:35:53.616298+00:00 [queued]>
[2025-06-17T01:35:57.330+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.extract.extract_and_load_to_staging manual__2025-06-17T01:35:53.616298+00:00 [queued]> dependency 'Trigger Rule' PASSED: True, The task instance did not have any upstream tasks.
[2025-06-17T01:35:57.345+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.extract.extract_and_load_to_staging manual__2025-06-17T01:35:53.616298+00:00 [queued]> dependency 'Pool Slots Available' PASSED: True, There are enough open slots in default_pool to execute the task
[2025-06-17T01:35:57.352+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.extract.extract_and_load_to_staging manual__2025-06-17T01:35:53.616298+00:00 [queued]> dependency 'Task Concurrency' PASSED: True, Task concurrency is not set.
[2025-06-17T01:35:57.354+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.extract.extract_and_load_to_staging manual__2025-06-17T01:35:53.616298+00:00 [queued]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2025-06-17T01:35:57.355+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.extract.extract_and_load_to_staging manual__2025-06-17T01:35:53.616298+00:00 [queued]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2025-06-17T01:35:57.355+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: globalsuperstore.extract.extract_and_load_to_staging manual__2025-06-17T01:35:53.616298+00:00 [queued]>
[2025-06-17T01:35:57.356+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-06-17T01:35:57.405+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract.extract_and_load_to_staging> on 2025-06-17 01:35:53.616298+00:00
[2025-06-17T01:35:57.433+0000] {standard_task_runner.py:63} INFO - Started process 682 to run task
[2025-06-17T01:35:57.440+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'globalsuperstore', 'extract.extract_and_load_to_staging', 'manual__2025-06-17T01:35:53.616298+00:00', '--job-id', '344', '--raw', '--subdir', 'DAGS_FOLDER/global_superstore_dw_etl.py', '--cfg-path', '/tmp/tmp1j1mir05']
[2025-06-17T01:35:57.442+0000] {standard_task_runner.py:91} INFO - Job 344: Subtask extract.extract_and_load_to_staging
[2025-06-17T01:35:57.448+0000] {cli_action_loggers.py:70} DEBUG - Calling callbacks: [<function default_action_log at 0x7fbba1929750>]
[2025-06-17T01:35:57.511+0000] {taskinstance.py:1042} DEBUG - previous_execution_date was called
[2025-06-17T01:35:57.518+0000] {task_command.py:426} INFO - Running <TaskInstance: globalsuperstore.extract.extract_and_load_to_staging manual__2025-06-17T01:35:53.616298+00:00 [running]> on host 9b7c60adfed6
[2025-06-17T01:35:57.519+0000] {settings.py:363} DEBUG - Disposing DB connection pool (PID 682)
[2025-06-17T01:35:57.520+0000] {settings.py:250} DEBUG - Setting up DB connection pool (PID 682)
[2025-06-17T01:35:57.520+0000] {settings.py:298} DEBUG - settings.prepare_engine_args(): Using NullPool
[2025-06-17T01:35:57.564+0000] {taskinstance.py:1042} DEBUG - previous_execution_date was called
[2025-06-17T01:35:57.568+0000] {taskinstance.py:1845} DEBUG - Clearing XCom data
[2025-06-17T01:35:57.613+0000] {retries.py:91} DEBUG - Running RenderedTaskInstanceFields.write with retries. Try 1 of 3
[2025-06-17T01:35:57.648+0000] {retries.py:91} DEBUG - Running RenderedTaskInstanceFields._do_delete_old_records with retries. Try 1 of 3
[2025-06-17T01:35:57.663+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='globalsuperstore' AIRFLOW_CTX_TASK_ID='extract.extract_and_load_to_staging' AIRFLOW_CTX_EXECUTION_DATE='2025-06-17T01:35:53.616298+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-17T01:35:53.616298+00:00'
[2025-06-17T01:35:57.664+0000] {__init__.py:115} DEBUG - Preparing lineage inlets and outlets
[2025-06-17T01:35:57.664+0000] {__init__.py:154} DEBUG - inlets: [], outlets: []
[2025-06-17T01:35:57.665+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-17T01:35:57.716+0000] {base.py:84} INFO - Using connection ID 'postgres' for task execution.
[2025-06-17T01:35:57.718+0000] {logging_mixin.py:188} INFO - ⏳ Đang tải dữ liệu từ bảng Category...
[2025-06-17T01:35:57.729+0000] {base.py:84} INFO - Using connection ID 'mysql' for task execution.
[2025-06-17T01:35:57.926+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/***/providers/common/sql/hooks/sql.py:263 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2025-06-17T01:35:58.383+0000] {logging_mixin.py:188} INFO - ✔ Đã lưu dữ liệu vào staging.stg_Category (3 dòng)
[2025-06-17T01:35:58.383+0000] {logging_mixin.py:188} INFO - ✔ Đã load Category → staging.stg_Category
[2025-06-17T01:35:58.384+0000] {logging_mixin.py:188} INFO - ⏳ Đang tải dữ liệu từ bảng Customer...
[2025-06-17T01:35:58.390+0000] {base.py:84} INFO - Using connection ID 'mysql' for task execution.
[2025-06-17T01:35:58.401+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/***/providers/common/sql/hooks/sql.py:263 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2025-06-17T01:36:00.671+0000] {logging_mixin.py:188} INFO - ✔ Đã lưu dữ liệu vào staging.stg_Customer (1590 dòng)
[2025-06-17T01:36:00.672+0000] {logging_mixin.py:188} INFO - ✔ Đã load Customer → staging.stg_Customer
[2025-06-17T01:36:00.673+0000] {logging_mixin.py:188} INFO - ⏳ Đang tải dữ liệu từ bảng Order_Details...
[2025-06-17T01:36:00.688+0000] {base.py:84} INFO - Using connection ID 'mysql' for task execution.
[2025-06-17T01:36:00.701+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/***/providers/common/sql/hooks/sql.py:263 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2025-06-17T01:36:02.493+0000] {retries.py:91} DEBUG - Running Job._fetch_from_db with retries. Try 1 of 3
[2025-06-17T01:36:02.514+0000] {retries.py:91} DEBUG - Running Job._update_heartbeat with retries. Try 1 of 3
[2025-06-17T01:36:02.559+0000] {job.py:214} DEBUG - [heartbeat]
[2025-06-17T01:36:07.598+0000] {retries.py:91} DEBUG - Running Job._fetch_from_db with retries. Try 1 of 3
[2025-06-17T01:36:07.605+0000] {retries.py:91} DEBUG - Running Job._update_heartbeat with retries. Try 1 of 3
[2025-06-17T01:36:07.618+0000] {job.py:214} DEBUG - [heartbeat]
[2025-06-17T01:36:09.762+0000] {logging_mixin.py:188} INFO - ✔ Đã lưu dữ liệu vào staging.stg_Order_Details (51252 dòng)
[2025-06-17T01:36:09.762+0000] {logging_mixin.py:188} INFO - ✔ Đã load Order_Details → staging.stg_Order_Details
[2025-06-17T01:36:09.763+0000] {logging_mixin.py:188} INFO - ⏳ Đang tải dữ liệu từ bảng Orders...
[2025-06-17T01:36:09.768+0000] {base.py:84} INFO - Using connection ID 'mysql' for task execution.
[2025-06-17T01:36:09.774+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/***/providers/common/sql/hooks/sql.py:263 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2025-06-17T01:36:12.647+0000] {retries.py:91} DEBUG - Running Job._fetch_from_db with retries. Try 1 of 3
[2025-06-17T01:36:12.654+0000] {retries.py:91} DEBUG - Running Job._update_heartbeat with retries. Try 1 of 3
[2025-06-17T01:36:12.690+0000] {job.py:214} DEBUG - [heartbeat]
[2025-06-17T01:36:13.741+0000] {logging_mixin.py:188} INFO - ✔ Đã lưu dữ liệu vào staging.stg_Orders (25035 dòng)
[2025-06-17T01:36:13.741+0000] {logging_mixin.py:188} INFO - ✔ Đã load Orders → staging.stg_Orders
[2025-06-17T01:36:13.742+0000] {logging_mixin.py:188} INFO - ⏳ Đang tải dữ liệu từ bảng Product...
[2025-06-17T01:36:13.747+0000] {base.py:84} INFO - Using connection ID 'mysql' for task execution.
[2025-06-17T01:36:13.755+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/***/providers/common/sql/hooks/sql.py:263 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2025-06-17T01:36:14.570+0000] {logging_mixin.py:188} INFO - ✔ Đã lưu dữ liệu vào staging.stg_Product (10292 dòng)
[2025-06-17T01:36:14.570+0000] {logging_mixin.py:188} INFO - ✔ Đã load Product → staging.stg_Product
[2025-06-17T01:36:14.571+0000] {logging_mixin.py:188} INFO - ⏳ Đang tải dữ liệu từ bảng Sub_Category...
[2025-06-17T01:36:14.576+0000] {base.py:84} INFO - Using connection ID 'mysql' for task execution.
[2025-06-17T01:36:14.580+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/***/providers/common/sql/hooks/sql.py:263 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2025-06-17T01:36:14.642+0000] {logging_mixin.py:188} INFO - ✔ Đã lưu dữ liệu vào staging.stg_Sub_Category (17 dòng)
[2025-06-17T01:36:14.643+0000] {logging_mixin.py:188} INFO - ✔ Đã load Sub_Category → staging.stg_Sub_Category
[2025-06-17T01:36:14.644+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-06-17T01:36:14.644+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-17T01:36:14.645+0000] {__init__.py:77} DEBUG - Lineage called with inlets: [], outlets: []
[2025-06-17T01:36:14.654+0000] {taskinstance.py:584} DEBUG - Clearing next_method and next_kwargs.
[2025-06-17T01:36:14.655+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=globalsuperstore, task_id=extract.extract_and_load_to_staging, run_id=manual__2025-06-17T01:35:53.616298+00:00, execution_date=20250617T013553, start_date=20250617T013557, end_date=20250617T013614
[2025-06-17T01:36:14.655+0000] {taskinstance.py:562} DEBUG - Task Duration set to 17.324413
[2025-06-17T01:36:14.670+0000] {cli_action_loggers.py:88} DEBUG - Calling callbacks: []
[2025-06-17T01:36:14.709+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-06-17T01:36:14.725+0000] {dagrun.py:931} DEBUG - number of tis tasks for <DagRun globalsuperstore @ 2025-06-17 01:35:53.616298+00:00: manual__2025-06-17T01:35:53.616298+00:00, state:running, queued_at: 2025-06-17 01:35:53.868474+00:00. externally triggered: True>: 7 task(s)
[2025-06-17T01:36:14.726+0000] {dagrun.py:952} DEBUG - number of scheduleable tasks for <DagRun globalsuperstore @ 2025-06-17 01:35:53.616298+00:00: manual__2025-06-17T01:35:53.616298+00:00, state:running, queued_at: 2025-06-17 01:35:53.868474+00:00. externally triggered: True>: 6 task(s)
[2025-06-17T01:36:14.727+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.transform.transform_dim_customers manual__2025-06-17T01:35:53.616298+00:00 [None]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2025-06-17T01:36:14.728+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.transform.transform_dim_customers manual__2025-06-17T01:35:53.616298+00:00 [None]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2025-06-17T01:36:14.728+0000] {taskinstance.py:2076} DEBUG - Dependencies all met for dep_context=None ti=<TaskInstance: globalsuperstore.transform.transform_dim_customers manual__2025-06-17T01:35:53.616298+00:00 [None]>
[2025-06-17T01:36:14.729+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.transform.transform_dim_products manual__2025-06-17T01:35:53.616298+00:00 [None]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2025-06-17T01:36:14.729+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.transform.transform_dim_products manual__2025-06-17T01:35:53.616298+00:00 [None]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2025-06-17T01:36:14.729+0000] {taskinstance.py:2076} DEBUG - Dependencies all met for dep_context=None ti=<TaskInstance: globalsuperstore.transform.transform_dim_products manual__2025-06-17T01:35:53.616298+00:00 [None]>
[2025-06-17T01:36:14.730+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.transform.transform_dim_locations manual__2025-06-17T01:35:53.616298+00:00 [None]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2025-06-17T01:36:14.730+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.transform.transform_dim_locations manual__2025-06-17T01:35:53.616298+00:00 [None]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2025-06-17T01:36:14.731+0000] {taskinstance.py:2076} DEBUG - Dependencies all met for dep_context=None ti=<TaskInstance: globalsuperstore.transform.transform_dim_locations manual__2025-06-17T01:35:53.616298+00:00 [None]>
[2025-06-17T01:36:14.731+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.transform.transform_dim_shipmode manual__2025-06-17T01:35:53.616298+00:00 [None]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2025-06-17T01:36:14.731+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.transform.transform_dim_shipmode manual__2025-06-17T01:35:53.616298+00:00 [None]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2025-06-17T01:36:14.732+0000] {taskinstance.py:2076} DEBUG - Dependencies all met for dep_context=None ti=<TaskInstance: globalsuperstore.transform.transform_dim_shipmode manual__2025-06-17T01:35:53.616298+00:00 [None]>
[2025-06-17T01:36:14.732+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.transform.transform_dim_date manual__2025-06-17T01:35:53.616298+00:00 [None]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2025-06-17T01:36:14.732+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.transform.transform_dim_date manual__2025-06-17T01:35:53.616298+00:00 [None]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2025-06-17T01:36:14.733+0000] {taskinstance.py:2076} DEBUG - Dependencies all met for dep_context=None ti=<TaskInstance: globalsuperstore.transform.transform_dim_date manual__2025-06-17T01:35:53.616298+00:00 [None]>
[2025-06-17T01:36:14.733+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.load.transform_fact_sales manual__2025-06-17T01:35:53.616298+00:00 [None]> dependency 'Trigger Rule' PASSED: False, Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 5 non-success(es). upstream_states=_UpstreamTIStates(success=0, skipped=0, failed=0, upstream_failed=0, removed=0, done=0, success_setup=0, skipped_setup=0), upstream_task_ids={'transform.transform_dim_locations', 'transform.transform_dim_shipmode', 'transform.transform_dim_products', 'transform.transform_dim_date', 'transform.transform_dim_customers'}
[2025-06-17T01:36:14.733+0000] {taskinstance.py:2066} DEBUG - Dependencies not met for <TaskInstance: globalsuperstore.load.transform_fact_sales manual__2025-06-17T01:35:53.616298+00:00 [None]>, dependency 'Trigger Rule' FAILED: Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 5 non-success(es). upstream_states=_UpstreamTIStates(success=0, skipped=0, failed=0, upstream_failed=0, removed=0, done=0, success_setup=0, skipped_setup=0), upstream_task_ids={'transform.transform_dim_locations', 'transform.transform_dim_shipmode', 'transform.transform_dim_products', 'transform.transform_dim_date', 'transform.transform_dim_customers'}
[2025-06-17T01:36:14.734+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.load.transform_fact_sales manual__2025-06-17T01:35:53.616298+00:00 [None]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2025-06-17T01:36:14.734+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.load.transform_fact_sales manual__2025-06-17T01:35:53.616298+00:00 [None]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2025-06-17T01:36:14.743+0000] {taskinstance.py:3503} INFO - 5 downstream tasks scheduled from follow-on schedule check
[2025-06-17T01:36:14.749+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
