[2025-06-16T16:10:45.151+0000] {taskinstance.py:1042} DEBUG - previous_execution_date was called
[2025-06-16T16:10:45.171+0000] {__init__.py:54} DEBUG - Loading core task runner: StandardTaskRunner
[2025-06-16T16:10:45.187+0000] {taskinstance.py:1042} DEBUG - previous_execution_date was called
[2025-06-16T16:10:45.192+0000] {base_task_runner.py:73} DEBUG - Planning to run as the  user
[2025-06-16T16:10:45.203+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-16T16:10:45.264+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.extract.extract_and_load_to_staging manual__2025-06-16T16:10:44.135355+00:00 [queued]> dependency 'Task Instance State' PASSED: True, Task state queued was valid.
[2025-06-16T16:10:45.265+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.extract.extract_and_load_to_staging manual__2025-06-16T16:10:44.135355+00:00 [queued]> dependency 'Task Instance Not Running' PASSED: True, Task is not in running state.
[2025-06-16T16:10:45.266+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.extract.extract_and_load_to_staging manual__2025-06-16T16:10:44.135355+00:00 [queued]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2025-06-16T16:10:45.267+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.extract.extract_and_load_to_staging manual__2025-06-16T16:10:44.135355+00:00 [queued]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2025-06-16T16:10:45.278+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.extract.extract_and_load_to_staging manual__2025-06-16T16:10:44.135355+00:00 [queued]> dependency 'Trigger Rule' PASSED: True, The task instance did not have any upstream tasks.
[2025-06-16T16:10:45.279+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: globalsuperstore.extract.extract_and_load_to_staging manual__2025-06-16T16:10:44.135355+00:00 [queued]>
[2025-06-16T16:10:45.287+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.extract.extract_and_load_to_staging manual__2025-06-16T16:10:44.135355+00:00 [queued]> dependency 'Pool Slots Available' PASSED: True, There are enough open slots in default_pool to execute the task
[2025-06-16T16:10:45.288+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.extract.extract_and_load_to_staging manual__2025-06-16T16:10:44.135355+00:00 [queued]> dependency 'Task Concurrency' PASSED: True, Task concurrency is not set.
[2025-06-16T16:10:45.288+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.extract.extract_and_load_to_staging manual__2025-06-16T16:10:44.135355+00:00 [queued]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2025-06-16T16:10:45.289+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.extract.extract_and_load_to_staging manual__2025-06-16T16:10:44.135355+00:00 [queued]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2025-06-16T16:10:45.294+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.extract.extract_and_load_to_staging manual__2025-06-16T16:10:44.135355+00:00 [queued]> dependency 'Trigger Rule' PASSED: True, The task instance did not have any upstream tasks.
[2025-06-16T16:10:45.294+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: globalsuperstore.extract.extract_and_load_to_staging manual__2025-06-16T16:10:44.135355+00:00 [queued]>
[2025-06-16T16:10:45.295+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-06-16T16:10:45.321+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract.extract_and_load_to_staging> on 2025-06-16 16:10:44.135355+00:00
[2025-06-16T16:10:45.328+0000] {standard_task_runner.py:63} INFO - Started process 1256 to run task
[2025-06-16T16:10:45.332+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'globalsuperstore', 'extract.extract_and_load_to_staging', 'manual__2025-06-16T16:10:44.135355+00:00', '--job-id', '176', '--raw', '--subdir', 'DAGS_FOLDER/global_superstore_dw_etl.py', '--cfg-path', '/tmp/tmptlnvbfto']
[2025-06-16T16:10:45.333+0000] {standard_task_runner.py:91} INFO - Job 176: Subtask extract.extract_and_load_to_staging
[2025-06-16T16:10:45.335+0000] {cli_action_loggers.py:70} DEBUG - Calling callbacks: [<function default_action_log at 0x7fa267925750>]
[2025-06-16T16:10:45.383+0000] {taskinstance.py:1042} DEBUG - previous_execution_date was called
[2025-06-16T16:10:45.388+0000] {task_command.py:426} INFO - Running <TaskInstance: globalsuperstore.extract.extract_and_load_to_staging manual__2025-06-16T16:10:44.135355+00:00 [running]> on host 9b7c60adfed6
[2025-06-16T16:10:45.389+0000] {settings.py:363} DEBUG - Disposing DB connection pool (PID 1256)
[2025-06-16T16:10:45.389+0000] {settings.py:250} DEBUG - Setting up DB connection pool (PID 1256)
[2025-06-16T16:10:45.390+0000] {settings.py:298} DEBUG - settings.prepare_engine_args(): Using NullPool
[2025-06-16T16:10:45.456+0000] {taskinstance.py:1042} DEBUG - previous_execution_date was called
[2025-06-16T16:10:45.461+0000] {taskinstance.py:1845} DEBUG - Clearing XCom data
[2025-06-16T16:10:45.506+0000] {retries.py:91} DEBUG - Running RenderedTaskInstanceFields.write with retries. Try 1 of 3
[2025-06-16T16:10:45.538+0000] {retries.py:91} DEBUG - Running RenderedTaskInstanceFields._do_delete_old_records with retries. Try 1 of 3
[2025-06-16T16:10:45.557+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='globalsuperstore' AIRFLOW_CTX_TASK_ID='extract.extract_and_load_to_staging' AIRFLOW_CTX_EXECUTION_DATE='2025-06-16T16:10:44.135355+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-16T16:10:44.135355+00:00'
[2025-06-16T16:10:45.558+0000] {__init__.py:115} DEBUG - Preparing lineage inlets and outlets
[2025-06-16T16:10:45.559+0000] {__init__.py:154} DEBUG - inlets: [], outlets: []
[2025-06-16T16:10:45.559+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-16T16:10:46.036+0000] {base.py:84} INFO - Using connection ID 'postgres' for task execution.
[2025-06-16T16:10:46.037+0000] {logging_mixin.py:188} INFO - ⏳ Đang tải dữ liệu từ bảng Category...
[2025-06-16T16:10:46.042+0000] {base.py:84} INFO - Using connection ID 'mysql' for task execution.
[2025-06-16T16:10:46.066+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/***/providers/common/sql/hooks/sql.py:263 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2025-06-16T16:10:46.133+0000] {logging_mixin.py:188} INFO - ✔ Đã load Category → staging.stg_Category
[2025-06-16T16:10:46.134+0000] {logging_mixin.py:188} INFO - ⏳ Đang tải dữ liệu từ bảng Customer...
[2025-06-16T16:10:46.138+0000] {base.py:84} INFO - Using connection ID 'mysql' for task execution.
[2025-06-16T16:10:46.144+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/***/providers/common/sql/hooks/sql.py:263 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2025-06-16T16:10:46.419+0000] {logging_mixin.py:188} INFO - ✔ Đã load Customer → staging.stg_Customer
[2025-06-16T16:10:46.420+0000] {logging_mixin.py:188} INFO - ⏳ Đang tải dữ liệu từ bảng Order_Details...
[2025-06-16T16:10:46.426+0000] {base.py:84} INFO - Using connection ID 'mysql' for task execution.
[2025-06-16T16:10:46.431+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/***/providers/common/sql/hooks/sql.py:263 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2025-06-16T16:10:50.362+0000] {retries.py:91} DEBUG - Running Job._fetch_from_db with retries. Try 1 of 3
[2025-06-16T16:10:50.370+0000] {retries.py:91} DEBUG - Running Job._update_heartbeat with retries. Try 1 of 3
[2025-06-16T16:10:50.382+0000] {job.py:214} DEBUG - [heartbeat]
[2025-06-16T16:10:52.971+0000] {logging_mixin.py:188} INFO - ✔ Đã load Order_Details → staging.stg_Order_Details
[2025-06-16T16:10:52.972+0000] {logging_mixin.py:188} INFO - ⏳ Đang tải dữ liệu từ bảng Orders...
[2025-06-16T16:10:52.980+0000] {base.py:84} INFO - Using connection ID 'mysql' for task execution.
[2025-06-16T16:10:52.988+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/***/providers/common/sql/hooks/sql.py:263 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2025-06-16T16:10:55.412+0000] {retries.py:91} DEBUG - Running Job._fetch_from_db with retries. Try 1 of 3
[2025-06-16T16:10:55.420+0000] {retries.py:91} DEBUG - Running Job._update_heartbeat with retries. Try 1 of 3
[2025-06-16T16:10:55.431+0000] {job.py:214} DEBUG - [heartbeat]
[2025-06-16T16:10:57.203+0000] {logging_mixin.py:188} INFO - ✔ Đã load Orders → staging.stg_Orders
[2025-06-16T16:10:57.203+0000] {logging_mixin.py:188} INFO - ⏳ Đang tải dữ liệu từ bảng Product...
[2025-06-16T16:10:57.211+0000] {base.py:84} INFO - Using connection ID 'mysql' for task execution.
[2025-06-16T16:10:57.218+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/***/providers/common/sql/hooks/sql.py:263 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2025-06-16T16:10:57.856+0000] {logging_mixin.py:188} INFO - ✔ Đã load Product → staging.stg_Product
[2025-06-16T16:10:57.857+0000] {logging_mixin.py:188} INFO - ⏳ Đang tải dữ liệu từ bảng Sub_Category...
[2025-06-16T16:10:57.861+0000] {base.py:84} INFO - Using connection ID 'mysql' for task execution.
[2025-06-16T16:10:57.866+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/***/providers/common/sql/hooks/sql.py:263 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2025-06-16T16:10:57.896+0000] {logging_mixin.py:188} INFO - ✔ Đã load Sub_Category → staging.stg_Sub_Category
[2025-06-16T16:10:57.896+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-06-16T16:10:57.897+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-16T16:10:57.897+0000] {__init__.py:77} DEBUG - Lineage called with inlets: [], outlets: []
[2025-06-16T16:10:57.904+0000] {taskinstance.py:584} DEBUG - Clearing next_method and next_kwargs.
[2025-06-16T16:10:57.905+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=globalsuperstore, task_id=extract.extract_and_load_to_staging, run_id=manual__2025-06-16T16:10:44.135355+00:00, execution_date=20250616T161044, start_date=20250616T161045, end_date=20250616T161057
[2025-06-16T16:10:57.905+0000] {taskinstance.py:562} DEBUG - Task Duration set to 12.625224
[2025-06-16T16:10:57.915+0000] {cli_action_loggers.py:88} DEBUG - Calling callbacks: []
[2025-06-16T16:10:57.972+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-06-16T16:10:57.988+0000] {dagrun.py:931} DEBUG - number of tis tasks for <DagRun globalsuperstore @ 2025-06-16 16:10:44.135355+00:00: manual__2025-06-16T16:10:44.135355+00:00, state:running, queued_at: 2025-06-16 16:10:44.178694+00:00. externally triggered: True>: 7 task(s)
[2025-06-16T16:10:57.989+0000] {dagrun.py:952} DEBUG - number of scheduleable tasks for <DagRun globalsuperstore @ 2025-06-16 16:10:44.135355+00:00: manual__2025-06-16T16:10:44.135355+00:00, state:running, queued_at: 2025-06-16 16:10:44.178694+00:00. externally triggered: True>: 6 task(s)
[2025-06-16T16:10:57.989+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.transform.transform_dim_customers manual__2025-06-16T16:10:44.135355+00:00 [None]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2025-06-16T16:10:57.990+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.transform.transform_dim_customers manual__2025-06-16T16:10:44.135355+00:00 [None]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2025-06-16T16:10:57.990+0000] {taskinstance.py:2076} DEBUG - Dependencies all met for dep_context=None ti=<TaskInstance: globalsuperstore.transform.transform_dim_customers manual__2025-06-16T16:10:44.135355+00:00 [None]>
[2025-06-16T16:10:57.991+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.transform.transform_dim_products manual__2025-06-16T16:10:44.135355+00:00 [None]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2025-06-16T16:10:57.991+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.transform.transform_dim_products manual__2025-06-16T16:10:44.135355+00:00 [None]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2025-06-16T16:10:57.991+0000] {taskinstance.py:2076} DEBUG - Dependencies all met for dep_context=None ti=<TaskInstance: globalsuperstore.transform.transform_dim_products manual__2025-06-16T16:10:44.135355+00:00 [None]>
[2025-06-16T16:10:57.992+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.transform.transform_dim_locations manual__2025-06-16T16:10:44.135355+00:00 [None]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2025-06-16T16:10:57.992+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.transform.transform_dim_locations manual__2025-06-16T16:10:44.135355+00:00 [None]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2025-06-16T16:10:57.992+0000] {taskinstance.py:2076} DEBUG - Dependencies all met for dep_context=None ti=<TaskInstance: globalsuperstore.transform.transform_dim_locations manual__2025-06-16T16:10:44.135355+00:00 [None]>
[2025-06-16T16:10:57.993+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.transform.transform_dim_shipmode manual__2025-06-16T16:10:44.135355+00:00 [None]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2025-06-16T16:10:57.993+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.transform.transform_dim_shipmode manual__2025-06-16T16:10:44.135355+00:00 [None]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2025-06-16T16:10:57.993+0000] {taskinstance.py:2076} DEBUG - Dependencies all met for dep_context=None ti=<TaskInstance: globalsuperstore.transform.transform_dim_shipmode manual__2025-06-16T16:10:44.135355+00:00 [None]>
[2025-06-16T16:10:57.994+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.transform.transform_dim_date manual__2025-06-16T16:10:44.135355+00:00 [None]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2025-06-16T16:10:57.994+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.transform.transform_dim_date manual__2025-06-16T16:10:44.135355+00:00 [None]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2025-06-16T16:10:57.994+0000] {taskinstance.py:2076} DEBUG - Dependencies all met for dep_context=None ti=<TaskInstance: globalsuperstore.transform.transform_dim_date manual__2025-06-16T16:10:44.135355+00:00 [None]>
[2025-06-16T16:10:57.995+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.load.transform_fact_sales manual__2025-06-16T16:10:44.135355+00:00 [None]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2025-06-16T16:10:57.995+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.load.transform_fact_sales manual__2025-06-16T16:10:44.135355+00:00 [None]> dependency 'Trigger Rule' PASSED: False, Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 5 non-success(es). upstream_states=_UpstreamTIStates(success=0, skipped=0, failed=0, upstream_failed=0, removed=0, done=0, success_setup=0, skipped_setup=0), upstream_task_ids={'transform.transform_dim_products', 'transform.transform_dim_locations', 'transform.transform_dim_customers', 'transform.transform_dim_date', 'transform.transform_dim_shipmode'}
[2025-06-16T16:10:57.995+0000] {taskinstance.py:2066} DEBUG - Dependencies not met for <TaskInstance: globalsuperstore.load.transform_fact_sales manual__2025-06-16T16:10:44.135355+00:00 [None]>, dependency 'Trigger Rule' FAILED: Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 5 non-success(es). upstream_states=_UpstreamTIStates(success=0, skipped=0, failed=0, upstream_failed=0, removed=0, done=0, success_setup=0, skipped_setup=0), upstream_task_ids={'transform.transform_dim_products', 'transform.transform_dim_locations', 'transform.transform_dim_customers', 'transform.transform_dim_date', 'transform.transform_dim_shipmode'}
[2025-06-16T16:10:57.996+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.load.transform_fact_sales manual__2025-06-16T16:10:44.135355+00:00 [None]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2025-06-16T16:10:58.003+0000] {taskinstance.py:3503} INFO - 5 downstream tasks scheduled from follow-on schedule check
[2025-06-16T16:10:58.006+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
