[2025-06-16T15:53:48.114+0000] {taskinstance.py:1042} DEBUG - previous_execution_date was called
[2025-06-16T15:53:48.143+0000] {__init__.py:54} DEBUG - Loading core task runner: StandardTaskRunner
[2025-06-16T15:53:48.169+0000] {taskinstance.py:1042} DEBUG - previous_execution_date was called
[2025-06-16T15:53:48.183+0000] {base_task_runner.py:73} DEBUG - Planning to run as the  user
[2025-06-16T15:53:48.195+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-16T15:53:48.250+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.transform.transform_dim_locations manual__2025-06-16T15:53:24.827849+00:00 [queued]> dependency 'Task Instance State' PASSED: True, Task state queued was valid.
[2025-06-16T15:53:48.251+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.transform.transform_dim_locations manual__2025-06-16T15:53:24.827849+00:00 [queued]> dependency 'Task Instance Not Running' PASSED: True, Task is not in running state.
[2025-06-16T15:53:48.251+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.transform.transform_dim_locations manual__2025-06-16T15:53:24.827849+00:00 [queued]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2025-06-16T15:53:48.252+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.transform.transform_dim_locations manual__2025-06-16T15:53:24.827849+00:00 [queued]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2025-06-16T15:53:48.264+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: globalsuperstore.transform.transform_dim_locations manual__2025-06-16T15:53:24.827849+00:00 [queued]>
[2025-06-16T15:53:48.274+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.transform.transform_dim_locations manual__2025-06-16T15:53:24.827849+00:00 [queued]> dependency 'Pool Slots Available' PASSED: True, There are enough open slots in default_pool to execute the task
[2025-06-16T15:53:48.274+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.transform.transform_dim_locations manual__2025-06-16T15:53:24.827849+00:00 [queued]> dependency 'Task Concurrency' PASSED: True, Task concurrency is not set.
[2025-06-16T15:53:48.275+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.transform.transform_dim_locations manual__2025-06-16T15:53:24.827849+00:00 [queued]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2025-06-16T15:53:48.275+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.transform.transform_dim_locations manual__2025-06-16T15:53:24.827849+00:00 [queued]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2025-06-16T15:53:48.284+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: globalsuperstore.transform.transform_dim_locations manual__2025-06-16T15:53:24.827849+00:00 [queued]>
[2025-06-16T15:53:48.284+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-06-16T15:53:48.323+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transform.transform_dim_locations> on 2025-06-16 15:53:24.827849+00:00
[2025-06-16T15:53:48.342+0000] {standard_task_runner.py:63} INFO - Started process 669 to run task
[2025-06-16T15:53:48.348+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'globalsuperstore', 'transform.transform_dim_locations', 'manual__2025-06-16T15:53:24.827849+00:00', '--job-id', '148', '--raw', '--subdir', 'DAGS_FOLDER/global_superstore_dw_etl.py', '--cfg-path', '/tmp/tmpafanzvcd']
[2025-06-16T15:53:48.350+0000] {standard_task_runner.py:91} INFO - Job 148: Subtask transform.transform_dim_locations
[2025-06-16T15:53:48.354+0000] {cli_action_loggers.py:70} DEBUG - Calling callbacks: [<function default_action_log at 0x7fa267925750>]
[2025-06-16T15:53:48.431+0000] {taskinstance.py:1042} DEBUG - previous_execution_date was called
[2025-06-16T15:53:48.439+0000] {task_command.py:426} INFO - Running <TaskInstance: globalsuperstore.transform.transform_dim_locations manual__2025-06-16T15:53:24.827849+00:00 [running]> on host 9b7c60adfed6
[2025-06-16T15:53:48.441+0000] {settings.py:363} DEBUG - Disposing DB connection pool (PID 669)
[2025-06-16T15:53:48.443+0000] {settings.py:250} DEBUG - Setting up DB connection pool (PID 669)
[2025-06-16T15:53:48.444+0000] {settings.py:298} DEBUG - settings.prepare_engine_args(): Using NullPool
[2025-06-16T15:53:48.497+0000] {taskinstance.py:1042} DEBUG - previous_execution_date was called
[2025-06-16T15:53:48.499+0000] {taskinstance.py:1845} DEBUG - Clearing XCom data
[2025-06-16T15:53:48.517+0000] {retries.py:91} DEBUG - Running RenderedTaskInstanceFields.write with retries. Try 1 of 3
[2025-06-16T15:53:48.544+0000] {retries.py:91} DEBUG - Running RenderedTaskInstanceFields._do_delete_old_records with retries. Try 1 of 3
[2025-06-16T15:53:48.557+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='globalsuperstore' AIRFLOW_CTX_TASK_ID='transform.transform_dim_locations' AIRFLOW_CTX_EXECUTION_DATE='2025-06-16T15:53:24.827849+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-16T15:53:24.827849+00:00'
[2025-06-16T15:53:48.558+0000] {__init__.py:115} DEBUG - Preparing lineage inlets and outlets
[2025-06-16T15:53:48.559+0000] {__init__.py:154} DEBUG - inlets: [], outlets: []
[2025-06-16T15:53:48.559+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-16T15:53:48.956+0000] {base.py:84} INFO - Using connection ID 'postgres' for task execution.
[2025-06-16T15:53:48.967+0000] {base.py:84} INFO - Using connection ID 'postgres' for task execution.
[2025-06-16T15:53:48.985+0000] {base.py:84} INFO - Using connection ID 'postgres' for task execution.
[2025-06-16T15:53:48.999+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/***/providers/common/sql/hooks/sql.py:263 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2025-06-16T15:53:49.616+0000] {logging_mixin.py:188} INFO - ✔ Đã transform và lưu dữ liệu vào warehouse.dim_location
[2025-06-16T15:53:49.626+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-06-16T15:53:49.627+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-16T15:53:49.628+0000] {__init__.py:77} DEBUG - Lineage called with inlets: [], outlets: []
[2025-06-16T15:53:49.639+0000] {taskinstance.py:584} DEBUG - Clearing next_method and next_kwargs.
[2025-06-16T15:53:49.640+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=globalsuperstore, task_id=transform.transform_dim_locations, run_id=manual__2025-06-16T15:53:24.827849+00:00, execution_date=20250616T155324, start_date=20250616T155348, end_date=20250616T155349
[2025-06-16T15:53:49.641+0000] {taskinstance.py:562} DEBUG - Task Duration set to 1.375424
[2025-06-16T15:53:49.655+0000] {cli_action_loggers.py:88} DEBUG - Calling callbacks: []
[2025-06-16T15:53:49.726+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-06-16T15:53:49.753+0000] {dagrun.py:931} DEBUG - number of tis tasks for <DagRun globalsuperstore @ 2025-06-16 15:53:24.827849+00:00: manual__2025-06-16T15:53:24.827849+00:00, state:running, queued_at: 2025-06-16 15:53:25.031651+00:00. externally triggered: True>: 6 task(s)
[2025-06-16T15:53:49.754+0000] {dagrun.py:952} DEBUG - number of scheduleable tasks for <DagRun globalsuperstore @ 2025-06-16 15:53:24.827849+00:00: manual__2025-06-16T15:53:24.827849+00:00, state:running, queued_at: 2025-06-16 15:53:25.031651+00:00. externally triggered: True>: 1 task(s)
[2025-06-16T15:53:49.755+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.load.transform_fact_sales manual__2025-06-16T15:53:24.827849+00:00 [None]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2025-06-16T15:53:49.756+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.load.transform_fact_sales manual__2025-06-16T15:53:24.827849+00:00 [None]> dependency 'Trigger Rule' PASSED: False, Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 1 non-success(es). upstream_states=_UpstreamTIStates(success=4, skipped=0, failed=0, upstream_failed=0, removed=0, done=4, success_setup=0, skipped_setup=0), upstream_task_ids={'transform.transform_dim_products', 'transform.transform_dim_customers', 'transform.transform_dim_locations', 'transform.transform_dim_date', 'transform.transform_dim_shipmode'}
[2025-06-16T15:53:49.757+0000] {taskinstance.py:2066} DEBUG - Dependencies not met for <TaskInstance: globalsuperstore.load.transform_fact_sales manual__2025-06-16T15:53:24.827849+00:00 [None]>, dependency 'Trigger Rule' FAILED: Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 1 non-success(es). upstream_states=_UpstreamTIStates(success=4, skipped=0, failed=0, upstream_failed=0, removed=0, done=4, success_setup=0, skipped_setup=0), upstream_task_ids={'transform.transform_dim_products', 'transform.transform_dim_customers', 'transform.transform_dim_locations', 'transform.transform_dim_date', 'transform.transform_dim_shipmode'}
[2025-06-16T15:53:49.757+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.load.transform_fact_sales manual__2025-06-16T15:53:24.827849+00:00 [None]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2025-06-16T15:53:49.765+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-16T15:53:49.769+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
