[2025-06-15T08:55:30.179+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-15T08:55:30.241+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: globalsuperstore.transform.transform_dim_customers scheduled__2025-06-14T00:00:00+00:00 [queued]>
[2025-06-15T08:55:30.255+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: globalsuperstore.transform.transform_dim_customers scheduled__2025-06-14T00:00:00+00:00 [queued]>
[2025-06-15T08:55:30.256+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-06-15T08:55:30.279+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transform.transform_dim_customers> on 2025-06-14 00:00:00+00:00
[2025-06-15T08:55:30.292+0000] {standard_task_runner.py:63} INFO - Started process 242 to run task
[2025-06-15T08:55:30.300+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'globalsuperstore', 'transform.transform_dim_customers', 'scheduled__2025-06-14T00:00:00+00:00', '--job-id', '303', '--raw', '--subdir', 'DAGS_FOLDER/global_superstore_dw_etl.py', '--cfg-path', '/tmp/tmposki61w0']
[2025-06-15T08:55:30.305+0000] {standard_task_runner.py:91} INFO - Job 303: Subtask transform.transform_dim_customers
[2025-06-15T08:55:30.384+0000] {task_command.py:426} INFO - Running <TaskInstance: globalsuperstore.transform.transform_dim_customers scheduled__2025-06-14T00:00:00+00:00 [running]> on host f3cca4675eb8
[2025-06-15T08:55:30.501+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='globalsuperstore' AIRFLOW_CTX_TASK_ID='transform.transform_dim_customers' AIRFLOW_CTX_EXECUTION_DATE='2025-06-14T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-06-14T00:00:00+00:00'
[2025-06-15T08:55:30.503+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-15T08:55:30.542+0000] {base.py:84} INFO - Using connection ID 'postgres' for task execution.
[2025-06-15T08:55:30.558+0000] {base.py:84} INFO - Using connection ID 'postgres' for task execution.
[2025-06-15T08:55:30.572+0000] {base.py:84} INFO - Using connection ID 'postgres' for task execution.
[2025-06-15T08:55:30.589+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/***/providers/common/sql/hooks/sql.py:263 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2025-06-15T08:55:31.423+0000] {logging_mixin.py:188} INFO - ✔ Đã transform và lưu dữ liệu vào warehouse.dim_customer
[2025-06-15T08:55:31.426+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-06-15T08:55:31.432+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-15T08:55:31.458+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=globalsuperstore, task_id=transform.transform_dim_customers, run_id=scheduled__2025-06-14T00:00:00+00:00, execution_date=20250614T000000, start_date=20250615T085530, end_date=20250615T085531
[2025-06-15T08:55:31.578+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-06-15T08:55:31.638+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-15T08:55:31.644+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
